### ISSUE TITLE
Sets Item List doesn't load while Editing

### ISSUE THREAD

**Issue by MerelyRBLX** [Anaminus/roblox-bug-tracker#106]
When a user attempts to edit one of his sets, the list of items in that set is cleared, and fails to repopulate. Because this feature is broken, users cannot organize the order of items within their sets.

![image](https://f.cloud.github.com/assets/5466234/1212797/8220543a-261e-11e3-88f5-59dce9d2bf37.png)

A request is sent to the SetsHandler to retrieve a list of items in the set, but the maximumRows parameter is undefined, so it returns an error page.

![image](https://f.cloud.github.com/assets/5466234/1212887/e1732132-261f-11e3-8b59-f42c1e519efb.png)

I believe the problem is on line 291 of /js/Sets/sets.js:
It appears that the totalNumberOfItemsInCurrentSet variable is not initialized.

![image](https://f.cloud.github.com/assets/5466234/1212942/b1f1e410-2620-11e3-81ba-3b6657cb34d3.png)

[Verified in Chrome, Firefox, and IE]

**Comment by Squidcod** [comment]
seems to be fine now
