### ISSUE TITLE
Sounds aren't properly validated

### ISSUE THREAD

**Issue by DigiTechs** [Anaminus/roblox-bug-tracker#118]
I just successfully uploaded a .wav (renamed to .mp3) that meets the requirements of the upload...

http://www.roblox.com/gravel-item?id=132309502

(title modified because better name was suggested... yay!)

**Comment by matthewdean** [comment]
Two weeks ago, [jeditkacheff](http://www.roblox.com/User.aspx?ID=7210880) indicated that ROBLOX may allow more audio formats to be uploaded:
> Smooth looping will be much easier to attain when we open up uploading of sounds of different types of files/codecs, OGG files in particular allow for smooth looping in our engine (as well as good quality/compression ratio) after doing some tests

So I think it's fine to close this issue, because if ROBLOX does anything, it will be to allow formats such as .wav to be uploaded

**Comment by DigiTechs** [comment]
That's good. By any chance can I have the source for that quote?

**Comment by einsteinK** [comment]
http://developer.roblox.com/forum/development-discussion/11954-weekly-api-update-january-8-2015-v0-179#129087
