### ISSUE TITLE
Forum 'Started by' is easily abused by client's login cookie.

### ISSUE THREAD

**Issue by Xnite515** [Anaminus/roblox-bug-tracker#121]
![hello](https://f.cloud.github.com/assets/5643870/1322734/9482beca-3446-11e3-9d87-cdd61b3f4210.png)
Easily abused by uppercase + lowercase letters; could be used for abusive or offensive reasons.

**Comment by Squidcod** [comment]
Is this still an issue?
If so could I get a quick breakdown of repro steps?

**Comment by matthewdean** [comment]
It used to be that by logging in with a different capitalization, any posts you made would use the capitalization with which you logged in. This appears to have been fixed.
