### ISSUE TITLE
Streaming cannot be controlled.

### ISSUE THREAD

**Issue by Quenty** [Anaminus/roblox-bug-tracker#130]
There is no API to control streaming, where one is very much required. Allowing ROBLOX users to control streaming is essential as without the ability to execute their own chunk management, it is impossible to create widescaled games. 

Streaming management should include the following abilities
* Allow users to select which items will be replicated on the client, and know/expect they will be there.  This is essential for loading separate areas seamlessly, much like ROBLOX's current halloween game fails to do.
* Allow users to deload items from the client, or at least mark them for garbage collection / they aren't required
* Be a setting, to toggle between automatic and user-set streaming (To avoid conflicts).

This should not be a hard feature to implement. 

This should be per a player, and controlled serverside (Client side obviously wouldn't work).

Without streaming management loading times must be increased as stuff cannot be preloaded, and essential parts cannot be loaded.  

Examples of usage can be provided, if request.

**Comment by matthewdean** [comment]
It appears that streaming has been unofficially dropped, so none of these suggestions will ever be implemented. I recommend splitting large places across multiple places or having the client create chunks of the map, since it is impossible to replicate objects to select players.
