### ISSUE TITLE
Add property that controls mouse sensitivity

### ISSUE THREAD

**Issue by hunte922** [Anaminus/roblox-bug-tracker#146]
Hi all, I'm not sure if this is a bug, but it's surely frustrating.
When in first person (zoomed in all the way), the camera turns either too fast or too slow, depending on http://wiki.roblox.com/index.php/FieldOfView_%28Property%29 .
I can't work with this when I'm trying to make a scoped weapon in first person - this bug makes it excruciatingly difficult to aim.

**Comment by Anaminus** [comment]
Mouse sensitivity can now be controlled by making a custom camera.
