### ISSUE TITLE
Changes to ModuleScript.Source should invalidate local cache

### ISSUE THREAD

**Issue by matthewdean** [Anaminus/roblox-bug-tracker#163]
On `gametest2.robloxlabs.com`, the return value of `require(ModuleScript)` is cached such that all subsequent calls on the same machine will return the same value. This makes testing ModuleScripts in studio tedious because cached ModuleScripts must be replaced with new ones.

The solution is to invalidate the cache whenever the source of a ModuleScript is changed. This will happen only in studio (not in online mode because source is not scriptable) so performance and security will not be affected.

**Comment by Domiii** [comment]
Testing `ModuleScript`s in the command line is impossible right now, since it never refreshes the script cache. Need to restart the entire Studio to get it to update. Maybe I am missing something?

**Comment by JodeRBX** [comment]
@Domiii Updating the value returned by require every time the underlying ModuleScript is changed is problematic because it is likely to violate many of the assumptions that the code requiring it is relying on. Take the following rather contrived example:

``` lua
local data = {}

local function set(key, val)
data[key] = val
end

local function get(key)
return data[key]
end

return {get = get, set = set}
```

If the cache is cleared, this code will get rerun, and all of the stuff stored in "data" will be deleted. This kind of pattern is fairly common, so breaking it isn't a good idea.

On the other hand, I think this is indicative of bigger design flaw in how the command bar works: namely, there is no way to reset the command bar's environment without reopening the place. Type `while wait() do print("hi") end` into the command bar and it'll run forever; events will never disconnect. There should be a reset button placed alongside the command bar, which would also make it safe to clear the ModuleScript cache.

**Comment by Domiii** [comment]
A clean [separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns) (specifically separation of data and code) would be *largely* beneficial :)

For example, Unity solves this by copying `public` and `serialized` state between (automatic!) script re-compilations and putting the developer in charge of deciding whether to re-run initialization and update loops for each component individually.

If Roblox could somehow be more explicit about what data is `public` and `serialized`, allow external entities to get a hold of that data and give some more control over how scripts are run in edit and game mode respectively, one could solve this much more elegantly than the current state of affairs that entirely prevents script updates in the editor. :/

**Comment by JodeRBX** [comment]
That's not really possible. To do that would mean updating Lua itself, which at best would be a massive effort to fix a small problem, and at worst would cause a bunch of people's code to mysteriously stop working. You're about as likely to convince Roblox to switch everything to C#.

**Comment by Domiii** [comment]
Actually, it might not be quite that complicated. [This SO answer](http://stackoverflow.com/a/2835433/2228771) provides a way to get all locals for the current scope. You could use this to easily get the "data of a script" in general. Of course, now one has to be able to determine what is private and what is public, but I think by providing a soft migration, this should be perfectly possible. Just like with `FilteringEnabled`, one could just deactivate the feature by default.

Unfortunately, the biggest hurdle for now is that Roblox does not currently implement `debug.getlocal` (or most `debug` functions for that matter).

I also understand that the use-case seems limited, but being able to separate code from data is rather necessary for (at least semi-)decent automated serialization mechanisms.

**Comment by JodeRBX** [comment]
First of all, Roblox doesn't "not implement debug yet", it *chooses* not to. Access to the debug library would allow users to break the sandbox.

But second of all, the only place where hot-swapping code is useful is in the editor; it serves no purpose in production. This is distinct from Unity, in which serialization can be used to aid the implementation of save files. Roblox is entirely online to begin with, so this approach makes little sense for it (instead, we have [data stores](http://wiki.roblox.com/index.php?title=Data_store), or external databases through [HttpService](http://wiki.roblox.com/index.php?title=API:Class/HttpService)).

Either way, this discussion has veered considerably from the original subject matter of the bug report, so I'm going to stop before a collaborator locks the thread. Consider a separate bug report if you want to continue discussion.
