### ISSUE TITLE
Inaccurate error message when Player:LoadNumber() fails

### ISSUE THREAD

**Issue by TheSneak** [Anaminus/roblox-bug-tracker#166]
I am calling Player.LoadNumber("Version") from a Script (not a LocalScript). Occasionally this call fails and reports this error message:

LocalScripts cannot use LoadNumber

The message is inaccurate as the call is not coming from a LocalScript.  This makes it difficult to understand the true source of the error.

**Comment by matthewdean** [comment]
Data persistence is deprecated so bugs like this will not be patched
