### ISSUE TITLE
Robux sign missing for paid access games on Games search

### ISSUE THREAD

**Issue by MerelyRBLX** [Anaminus/roblox-bug-tracker#169]
![image](https://f.cloud.github.com/assets/5466234/1730238/27e52aac-62d9-11e3-86c0-6b2506624b89.png)

When a paid access game appears in the search results of the games page, the robux sign is notably absent.

Bug first reported by enyahs7 on the RbxDev forums.

**Comment by Squidcod** [comment]
appears to no longer be an issue
