### ISSUE TITLE
The ability to selectively ray cast parts

### ISSUE THREAD

**Issue by DrChill** [Anaminus/roblox-bug-tracker#170]
Currently you can't just ray cast for collision with just one Instance, you must use an ignore list of all Instances you don't want, which does not sound very efficient.

In a game I am co-developing on we do a large number of ray casts, because we are developing a RTS, we have had up to (and probably more) than 100 units in a server, at maximum units will do 16 ray casts every 0.05 seconds, meaning that up to 1600 ray casts are being done on every Instance in the server.

In one game we had a player who had like 200 planes, after someone else built a few more tanks, the game literally froze, not lagged up and moved slowly, just froze until someone gave up and sold off their tanks.

**Comment by matthewdean** [comment]
You can now raycast with a whitelist: http://wiki.roblox.com/index.php?title=API:Class/Workspace/FindPartOnRayWithWhitelist
