### ISSUE TITLE
ROBLOX Studio Download on Website only works for Windows

### ISSUE THREAD

**Issue by Quenty** [Anaminus/roblox-bug-tracker#171]
The download on http://www.roblox.com/develop is only for Windows. There should be an alternate download for mac users.

**Comment by Squidcod** [comment]
Appears to be an out of date issue.

**Comment by SNCPlay42** [comment]
Still appears to be an issue to me, unless this link changes when viewed from a mac:

![studio_download](https://cloud.githubusercontent.com/assets/5455518/9050350/db53f980-3a44-11e5-9d7c-7a90faab6c3f.png)

**Comment by Squidcod** [comment]
When I hopped on a mac there was no download link

**Comment by matthewdean** [comment]
If my memory serves me, the link is hidden because there is no executable for installing studio on a Mac, and thus nothing to link to.
