### ISSUE TITLE
Graphics bugs at extreme coordinates

### ISSUE THREAD

**Issue by alexrocks911** [Anaminus/roblox-bug-tracker#179]
1) Get a Teleport tool in your Backpack.
2) Keep clicking on the normal skybox to get out but do not die/reset.
3) Your character will look strange and a bit transparent and the camera glitches to be at on angle until you reset.

Video: http://www.youtube.com/watch?v=R4iBL9Au3-U

**Comment by matthewdean** [comment]
This is a consequence of using floating-point numbers:

http://gamedev.stackexchange.com/questions/23848/why-does-the-resolution-of-floating-point-numbers-decrease-further-from-an-origi

**Comment by Anaminus** [comment]
I wouldn't say it was a problem with floating-point, because it occurred at such low coordinates. Regardless, the issue in question was fixed a long while ago.
