### ISSUE TITLE
Sound Settings

### ISSUE THREAD

**Issue by Usering** [Anaminus/roblox-bug-tracker#188]
I know that you can enable/disable sounds from external programs in Windows, but with the Mac, there is no way to disable sounds. What if you're listening to music, or talking to someone in Skype and there is a lot of sound that you don't want to hear. This is much needed and is something that every game except Roblox contains.

**Comment by matthewdean** [comment]
There is now a volume slider
![image](https://cloud.githubusercontent.com/assets/4099467/5773633/20cca2f4-9d2a-11e4-9404-e41410c51142.png)
