### ISSUE TITLE
The mobile website shows an error message on the profile pages of banned users

### ISSUE THREAD

**Issue by mark-otaris** [Anaminus/roblox-bug-tracker#191]
The main website was recently updated to show the profiles of temporarily banned and terminated users. The mobile website, however, gives an error message when one attempts to view the profile page of a banned user ([example](https://m.roblox.com/users/1337)). For consistency, this should be fixed. However, because this is the only way to know if a user is banned, it would be nice to have another way to get that information (see #193).

**Comment by matthewdean** [comment]
It appears that the website no longer shows the profiles of deleted users. I am not sure about temporary bans.

But a user's moderation status is considered private information so there will never be a public API for it.
