### ISSUE TITLE
InsertService:Insert should be deprecated

### ISSUE THREAD

**Issue by ghost** [Anaminus/roblox-bug-tracker#198]
The `InsertService:Insert` method, called on an object, is equivalent to setting the `Parent` property of that object to the workspace. However, this method causes problems in some cases, as indicated by [HotThoth](http://www.roblox.com/User.aspx?ID=9881199), and is not useful since it is easier to change the `Parent` property manually. It should be deprecated and the summary in the `ReflectionMetadata.xml` file should be updated to indicate that the `Parent` property should be set manually to the workspace instead.

**Comment by matthewdean** [comment]
Fixed by TheGamer101.
