### ISSUE TITLE
Workspace:FindPartOnRay() should return a face normal

### ISSUE THREAD

**Issue by kyle-emmerich** [Anaminus/roblox-bug-tracker#209]
This would be very useful for lots of things, I don't even need to explain. It's better to have it in the API itself rather than using some buggy workaround that can't account for millions of edge cases and will be slow because it's written in Lua.

**Comment by matthewdean** [comment]
Quoting @SolarCrane from a week ago:
> A frequently requested feature regarding the FindPartOnRay API has been released to production.
> FindPartOnRay and FindPartOnRayWithIgnoreList API functions now return the normal of the surface that was hit:
> * It is returned as a third value after the hit part and hit position.
> * The surface normal will be in world space.
> * There will be no additional performance cost to the FindPartOnRay function.
> * It will work with all physical objects in the roblox workspace including CSGs and Terrain.
> You can check out the api on the wiki:
> http://wiki.roblox.com/index.php?title=FindPartOnRay
