### ISSUE TITLE
No way to get interpolated rendering CFrame

### ISSUE THREAD

**Issue by Quenty** [Anaminus/roblox-bug-tracker#256]
There is no way to retrieve a ROBLOX's part interpolated rendering CFrame, which makes it impossible to manually create animations relative to a moving part. 

<blockquote class="twitter-tweet" lang="en"><p><a href="https://twitter.com/Quenty">@Quenty</a> <a href="https://twitter.com/MerelyRBLX">@MerelyRBLX</a> Hint: adding a feature req to github issues or rbxdev for rendering cframe might be worthwhile.</p>&mdash; Arseny Kapoulkine (@zeuxcg) <a href="https://twitter.com/zeuxcg/statuses/450427383640629248">March 31, 2014</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by matthewdean** [comment]
BasePart:GetRenderCFrame() now exists.

**Comment by Quenty** [comment]
This is immensely satisfying.
