### ISSUE TITLE
Creating a script while game is running causes crash

### ISSUE THREAD

**Issue by Anaminus** [Anaminus/roblox-bug-tracker#258]
Steps by @The0neThe0nly:
1. Open studio and open a new place (CTRL + N)
2. Hit the "Play" button
3. Create a script and open it
4. Hit the reset button while it is opened
5. Create another script somewhere
6. Observe the pretty crash message that shows up

**Comment by The0neThe0nly** [comment]
Yes, this bug has been fixed.
