### ISSUE TITLE
Add event that fires after NetworkReplicator.RequestCharacter is called

### ISSUE THREAD

**Issue by Anaminus** [Anaminus/roblox-bug-tracker#259]
Normally, when a client is ready for the character to load, it calls [NetworkReplicator.RequestCharacter](http://anaminus.github.io/api/class/NetworkReplicator.html#memberRequestCharacter). However, when [Players.CharacterAutoLoads](http://anaminus.github.io/api/class/Players.html#memberCharacterAutoLoads) is false, this request is simply ignored, and not handled in any way. There is no clean way for a server script to tell when the client is ready, so I suggest an event that fires after RequestCharacter has been called.

**Comment by Anaminus** [comment]
Made obsolete by ReplicatedFirst.

**Comment by Anaminus** [comment]
ReplicatedFirst isn't enabled yet. :|

**Comment by hockeychaos** [comment]
But it is? Is there a doc or something somewhere that says it isn't?

**Comment by einsteinK** [comment]
I remember hearing from staff that it is enabled, but doesn't work in studio.
(I quickly checked using Start Server & Start Player, and the responsible corescript doesn't seem to load)

**Comment by Anaminus** [comment]
> doesn't work in studio

I suppose that's what I mean. Though I'm not sure why it would be enabled online, but not in studio. I'd at least say that it's not yet fully released.

**Comment by Anaminus** [comment]
ReplicatedFirst now works in studio.
