### ISSUE TITLE
3D Sound positioning is buggy

### ISSUE THREAD

**Issue by Anaminus** [Anaminus/roblox-bug-tracker#26]
A sound emitting from a part with a far position (i.e. 5000,0,0) sounds very buggy.

**Comment by hockeychaos** [comment]
do we know if this is still an issue? any repro place?

**Comment by SNCPlay42** [comment]
There's a repro file in the repository: https://github.com/Anaminus/roblox-bug-tracker/tree/master/issues/26

**Comment by Anaminus** [comment]
Fixed.

**Comment by Vectricity** [comment]
Thank you.
