### ISSUE TITLE
Add Players.GetMaxPlayers function

### ISSUE THREAD

**Issue by Anaminus** [Anaminus/roblox-bug-tracker#269]
The [Players.MaxPlayers](http://anaminus.github.io/api/class/Players.html#memberMaxPlayers) property enforces the maximum number of players that may be in a server. It is locked so that it cannot be changed while a server is running. Knowing this value can be useful, but it cannot be read by a normal script without also unlocking it. So, I purpose a GetMaxPlayers function, which returns the value of MaxPlayers.

Alternatively, a Player.SetMaxPlayers function (locked, called by server) could be added, and then MaxPlayers can be unlocked, and made read-only. This would be more consistent with the rest of the API, where it is common to have a locked function that sets a restricted value (e.g. [Players.SetChatStyle](http://anaminus.github.io/api/class/Players.html#memberSetChatStyle)).

**Comment by RobloxCodeWriter** [comment]
This will be available soon.

**Comment by matthewdean** [comment]
Players.MaxPlayers is now readable from normal scripts.
