### ISSUE TITLE
Search engines indexing IP addresses of www.roblox.com

### ISSUE THREAD

**Issue by matthewdean** [Anaminus/roblox-bug-tracker#291]
http://209.15.15.253/
http://209.15.211.168/
http://209.15.211.170/

Particularly annoying because they show up in Google search results:
![](https://cloud.githubusercontent.com/assets/4099467/2813713/dfaf6504-ce94-11e3-8bff-fd82a986329b.png)

And if you try going to the HTTPS version of the site:
![](https://cloud.githubusercontent.com/assets/4099467/2813719/4b1457aa-ce95-11e3-95f9-776738cd07c0.png)

**Comment by Squidcod** [comment]
looks fixed
