### ISSUE TITLE
Right clicking in studio in solo test mode results in a massive duplicated list. 

### ISSUE THREAD

**Issue by Quenty** [Anaminus/roblox-bug-tracker#294]
When you right click in studio in solo test mode, plugins are duplicated in the enable/disable list.

![image](https://cloud.githubusercontent.com/assets/1774409/2810247/6a614e64-cdab-11e3-8af8-a815c55a196e.png)

**Comment by Anaminus** [comment]
This appears to be SystemMenu, which is no longer officially supported. This isn't an issue in RibbonBar, because plugin toolbars cannot be toggled.

**Comment by einsteinK** [comment]
It can be that it still happens, but can't be seen due no method of seeing those bars.
Basicly, studio recognises all plugins, including the one in the frozen instance of studio.
(Play Solo > New instance opens, but old instance is frozen and kept, until you press Reset)
