### ISSUE TITLE
Internal errors have empty error messages

### ISSUE THREAD

**Issue by matthewdean** [Anaminus/roblox-bug-tracker#295]
Certain actions, such as attempting to access a property of a RobloxLocked object, result in the following error message being written to the output:
```lua
print(Game.CoreGui.Version)
--> An error occured
```
However, if we capture the error message with `pcall`, we get the empty string:
```lua
local success, err = pcall(function() print(Game.CoreGui.Version) end)
print(success) --> false
print(err == "") --> true
```
In this case, the second return value from `pcall` should be `"An error occured"` instead of the empty string.

**Comment by RobloxCodeWriter** [comment]
This should be fixed.
