### ISSUE TITLE
Instances in the game tree do not have strong Lua references

### ISSUE THREAD

**Issue by Anaminus** [Anaminus/roblox-bug-tracker#302]
Normally, if an object is in a weak table, and it does not have any other strong references to it, then it will get garbage-collected.

The same is true for Instances. However, even when the Instance is in the game tree (e.g. Game.Workspace.BasePlate), then it will still get collected, and removed from the weak table.

```lua
weak = setmetatable({},{__mode = 'v'})

weak.Part = Instance.new('Part',Workspace)
print(weak.Part, Workspace.Part) --> Part Part

-- some time later...
print(weak.Part, Workspace.Part) --> nil Part
```
As you can see, the Part has no other references to it. But even though it is still in the game tree, it gets removed from the weak table.

**Comment by zeux** [comment]
Lua GC is not aware of instance lifetimes; this is by design and extremely unlikely to change.

**Comment by Anaminus** [comment]
This can be worked around by having the following script running somewhere:

```lua
local ref = {}

game.DescendantAdded:connect(function(object)
	ref[object] = true
end)

game.DescendantRemoving:connect(function(object)
	ref[object] = nil
end)
```

Since it's not likely to change, and there's a decent-enough workaround, it seems safe to close this.
