### ISSUE TITLE
Personal Servers still have the old "Games" tab design

### ISSUE THREAD

**Issue by Gskartwii** [Anaminus/roblox-bug-tracker#327]
Steps to reproduce:
1. Go to any Personal Server place (e.g. http://www.roblox.com/X-Legion-Germania-RP-place?id=48403860)
2. Click on "Games" on the bottom of the page
You will see that it has the old design.

**Comment by Gskartwii** [comment]
Since the new game page layout update, the Game Instances page doesn't load at all with personal servers.

**Comment by matthewdean** [comment]
So this particular issue doesn't happen anymore.
