### ISSUE TITLE
"Online Friends" tab only shows portion of active friends

### ISSUE THREAD

**Issue by MerelyRBLX** [Anaminus/roblox-bug-tracker#353]
The 'Online Friends' tab at the bottom of the page (hit the 'Online' button at the bottom of the page first) doesn't display all your online friends. It only displays a partial amount. I am using Google Chrome and Windows 8.

Reported by AmiracIe.

**Comment by matthewdean** [comment]
Doesn't appear to be happening anymore, now that there is a hard limit of 200 friends.
