### ISSUE TITLE
Tool not immediately welded to arm when equipped

### ISSUE THREAD

**Issue by MerelyRBLX** [Anaminus/roblox-bug-tracker#355]
Steps:
1. Join a game that has at least 1 tool
1. Equip the tool
2. The tool is parented to Workspace and appears in the last position it was equipped from
3. After approximately 1/4th to 1/2th of a second, the tool "teleports" to the position of your arm and is welded

Expected behavior: When I equip a tool, the tool immediately appears in my hand, without "teleporting" from its last position.

![gif8](https://cloud.githubusercontent.com/assets/5466234/3566550/937f2b6e-0af9-11e4-8fac-6a1dd469659a.gif)

**Comment by matthewdean** [comment]
@zeux How hard would it be to the implement this on the C++ side? Otherwise we can resort to einsteinK's suggestion of doing it from a CoreScript.

**Comment by zeux** [comment]
We are planning to fix this. I think the fix would have to be on the C++ side at least partially. I'm fuzzy on the details...

**Comment by hockeychaos** [comment]
We actually have an API to do this, and the new backpack script uses this. We actually tried turning it on recently, but some games (like apoc rising) had issues with how the welds were being created. I think twentycharacters is looking into why.

**Comment by Gskartwii** [comment]
Appears to be fixed.
