### ISSUE TITLE
"Send reply" message is disabled after error occurs

### ISSUE THREAD

**Issue by MerelyRBLX** [Anaminus/roblox-bug-tracker#356]
When you attempt to send or reply to a message and an error occurs (rarely happens), the "Send reply" button is disabled, which prevents you from retrying.

![image](https://cloud.githubusercontent.com/assets/5466234/3566646/5616c486-0afd-11e4-9fd1-3bd11a34eb79.png)

...

![image](https://cloud.githubusercontent.com/assets/5466234/3566645/436ae8da-0afd-11e4-9448-b8d06709ac63.png)

**Comment by matthewdean** [comment]
Fixed with the rewrite
