### ISSUE TITLE
Allow the Mouse Lock UI element to be removed

### ISSUE THREAD

**Issue by TheSneak** [Anaminus/roblox-bug-tracker#416]
Please provide functionality to hide the Mouse Lock UI element as is currently possible for the chat, backpack, health and leaderboard elements. 

I have a 2D card game that uses only the UI, so mouse lock is irrelevant and the UI element takes up valuable screen space.

**Comment by RobloxCodeWriter** [comment]
This can now be disabled for all players and the UI icon will not appear.
