### ISSUE TITLE
Pressing the play button on any audio on the current page resumes the first played audio

### ISSUE THREAD

**Issue by Anaminus** [Anaminus/roblox-bug-tracker#417]
1. Go to an [audio asset](http://www.roblox.com/HalloweenThunder-wav-item?id=12222030).
2. Press any play button (current audio, recommended, etc), and pause it.
3. Press another play button.
4. Observe how the first audio plays instead of the clicked audio.

**Comment by matthewdean** [comment]
Fixed.
