### ISSUE TITLE
Guest property shouldn't be determined based on negative userId

### ISSUE THREAD

**Issue by blocco** [Anaminus/roblox-bug-tracker#424]
(This is made to disambiguate #339)

The `Guest` property in players is automatically set to true whenever a userId is negative.  I realize that this is intentional, as all guests have negative userIds.  This becomes problematic when testing in local test servers, but only to the point that it prevents the user from chatting.

Since the prevention of chat is not included in the scope of this issue, that will be covered in a separate issue (#425).

**Comment by matthewdean** [comment]
I don't think this a bug anymore, because it's not causing any unexpected behavior. Any player with a negative userId is a guest.
