### ISSUE TITLE
Unable to chat in local test servers

### ISSUE THREAD

**Issue by blocco** [Anaminus/roblox-bug-tracker#425]
(This is made to disambiguate #339)

Since, as discussed in #424, the `Guest` property is set to true whenever a player's userId is negative, all players in local test servers have negative userIds.  Internally, the `Guest` property also prevents a player from chatting without using super safe chat.  Because of this combination of things, there is an inability to chat in local test servers.

This issue only discusses the impact of the `Guest` property on the ability to chat in local test servers.  It does not deal with the automatic setting of the `Guest` property by negative userIds.  For that, see #424.

**Comment by SolarCrane** [comment]
You are now able to chat in Studio with the updates from the Studio team and the new chat script.
So I think we should close this issue.

**Comment by matthewdean** [comment]
I just want to say thank you to whoever on the Studio team made this possible. This is a fantastic feature!
