### ISSUE TITLE
Humanoid.Health value not maintained upon game start

### ISSUE THREAD

**Issue by TheSneak** [Anaminus/roblox-bug-tracker#426]
A model containing a Humanoid with Health and MaxHealth properties set to 5000 does not maintain those values when the game is played. Instead, Health reverts to 100.

This is a simple issue to duplicate. The following model contains a Humanoid with Health and MaxHealth properties set to 5000. Put this model in a new place and start it (F7). The Health property of the Humanoid will be set to 100 rather than the value 5000 that was set in Studio.

http://www.roblox.com/Humanoid-Health-Problem-Demo-item?id=172856395

**Comment by matthewdean** [comment]
This has been fixed for all humanoids serialized after this point. The solution was to change this:

```xml
<float name="Health">5000</float>
<float name="MaxHealth">5000</float>
```

To:

```xml
<float name="Health_XML">5000</float>
<float name="MaxHealth">5000</float>
```

Health_XML doesn't respect the MaxHealth property, but it's nonscriptable so it can only be used by the serializer.
