### ISSUE TITLE
Health/MaxHealth values of a Humanoid are not properly propagated to clients

### ISSUE THREAD

**Issue by TheSneak** [Anaminus/roblox-bug-tracker#427]
If a Humanoid has its Health and MaxHealth properties set to greater than 100 by a script, the bug described in #426 is partially averted. The server will display the correct values set by the script. However, clients will still see the value 100 for the Humanoid Health property.

The following model contains a Humanoid. At runtime, the Health and MaxHealth properties of the Humanoid are set to 5000 by a script. Viewing these properties in the server shows them having been correctly set by the script. However, after attaching a client, the client will be shown the value 100 for the Humanoid's Health property.

http://www.roblox.com/Humanoid-Health-Problem-Demo-Part-2-item?id=172858085

**Comment by matthewdean** [comment]
Fixed.
