### ISSUE TITLE
'Upgrade Now' button is not properly aligned on de.roblox.com

### ISSUE THREAD

**Issue by Bluji** [Anaminus/roblox-bug-tracker#434]
What should happen: The 'upgrade now' button on the german version needs to be centered in the sidebar.

Tested it on Google Chrome, Firefox, and Internet Explorer.
![button align glitch](https://cloud.githubusercontent.com/assets/8538964/4033907/bc7d06be-2c80-11e4-9583-cb31bda9e8e9.png)
![button align glitch de](https://cloud.githubusercontent.com/assets/8538964/4033913/c0b61f04-2c80-11e4-9298-266f5d03cfe3.png)

**Comment by tobyteel** [comment]
The german site is no longer available.
