### ISSUE TITLE
Enhancement: Stop using mask when processing badge images

### ISSUE THREAD

**Issue by TheSneak** [Anaminus/roblox-bug-tracker#439]
As a game developer, I want to use rounded rectangular shaped badges with anti-aliased edges and small overlays at the bottom center of the badge. The circular mask that is applied to badges when they are generated boxes me in to a specific, pre-defined mold which doesn't match the ambiance I'm seeking for my game. To create the badges I desire, they must be made small enough to fit within the circular mask resulting in a visually unimpressive badge.

Please stop applying the circular mask when processing images or make it optional.

**Comment by matthewdean** [comment]
All newly uploaded badges will use an anti-aliased circular mask. That being said, I don't believe the badge mask will ever go away.
