### ISSUE TITLE
Specific hat cannot be worn

### ISSUE THREAD

**Issue by MerelyRBLX** [Anaminus/roblox-bug-tracker#441]
Reported by Hustled
http://www.roblox.com/user.aspx?id=30737673

![image](https://cloud.githubusercontent.com/assets/5466234/4100460/26337040-3099-11e4-9e88-daeff6f2d875.png)
http://www.roblox.com/Gnome-item?id=45941295

This Gnome hat is not visible when worn on your character, both on the website and in-game. When I attempted to insert the hat using InsertService, I got the following error.

![image](https://cloud.githubusercontent.com/assets/5466234/4100459/0e4a9648-3099-11e4-99e1-0c704328b2f4.png)

**Comment by matthewdean** [comment]
Fixed.
