### ISSUE TITLE
Inconsistent abbreviation for thousands on Profile page

### ISSUE THREAD

**Issue by MerelyRBLX** [Anaminus/roblox-bug-tracker#442]
Reported by Robotmega http://www.roblox.com/User.aspx?ID=3095250

On the new navigation and most pages, thousands are abbreviated with a capital "1K+"

However, on the Profile page, if you have more than 1000 friends, it displays as "1k+"

![image](https://cloud.githubusercontent.com/assets/5466234/4100476/6f8a97a4-309a-11e4-9444-d4f31160046d.png)

**Comment by Squidcod** [comment]
Profile probably going to be a deprecated issue.
