### ISSUE TITLE
Forum CSS doesn't load when "Forum" is lowercase

### ISSUE THREAD

**Issue by MerelyRBLX** [Anaminus/roblox-bug-tracker#444]
http://www.roblox.com/forum/default.aspx
![image](https://cloud.githubusercontent.com/assets/5466234/4112873/861dc646-323c-11e4-9137-1f3f18a570f7.png)

Compare that to:

http://www.roblox.com/Forum/default.aspx
![image](https://cloud.githubusercontent.com/assets/5466234/4112875/8ede79b0-323c-11e4-8494-90fb326ddbbe.png)

**Comment by Squidcod** [comment]
Wont fix unless you can find ROBLOX nav that causes this.

**Comment by Anaminus** [comment]
It's fixed anyway. Going to http://www.roblox.com/forum/default.aspx loads the CSS.

**Comment by MerelyRBLX** [comment]
I fixed this last week.
