### ISSUE TITLE
PlayerAdded event does not fire for LocalScripts

### ISSUE THREAD

**Issue by MerelyRBLX** [Anaminus/roblox-bug-tracker#445]
Reproduction steps:

Create a localscript in StarterGui with the following code:

```lua
game:GetService("Players").PlayerAdded:connect(function(player)
    print("PlayerAdded fired for " .. player.Name)
end)

game:GetService("Players").ChildAdded:connect(function(player)
    print("ChildAdded fired for " .. player.Name)
end)
```
1. Join an online game
2. Have another player join the game
3. Open up the developer console and notice that the ChildAdded event fired, but not PlayerAdded.

**Comment by matthewdean** [comment]
It's probably worth noting that PlayerRemoving also doesn't fire on the client.

**Comment by matthewdean** [comment]
Now both events fire on the client.

**Comment by SNCPlay42** [comment]
Why was this reopened?

**Comment by magiccube3** [comment]
Unsure, they events do fire on the client now, no?

**Comment by matthewdean** [comment]
Finally fixed.
