### ISSUE TITLE
ScriptAnalyzer treats hexadecimal number literals as invalid numbers

### ISSUE THREAD

**Issue by Gskartwii** [Anaminus/roblox-bug-tracker#464]
Steps to reproduce:

1. Create a new script in the workspace
2. Put the following code in there:

	`print(0x2)`
3. Open up the Script Analyzer and you will see the following error:
	Error: (1,7) Malformed number

However, when you start a server it will just print "2" to the output.

**Comment by zeux** [comment]
Fixed with 1/28 Studio release.
