### ISSUE TITLE
Error/Bug in Character Customize

### ISSUE THREAD

**Issue by UnionistsRBLX** [Anaminus/roblox-bug-tracker#479]
When I try customizing my character, it still keeps giving me the image of my old character in preview.
![http___makeagif com__media_10-05-2014_mp9ezn](https://cloud.githubusercontent.com/assets/8968071/4517700/b4fe9bc6-4c4e-11e4-8687-d7af7acea072.gif)

**Comment by matthewdean** [comment]
I cannot reproduce this error, so I'm closing the issue. If this issue is still happening for you, please provide reproduction steps.
