### ISSUE TITLE
Builder's Club Icon not visible

### ISSUE THREAD

**Issue by PeteyK473** [Anaminus/roblox-bug-tracker#481]
On the user Hayzukin (http://www.roblox.com/User.aspx?ID=165381) his Builder's Club icon is not visible in the corner of the user's character.
![bc icon](https://cloud.githubusercontent.com/assets/8633691/4566430/ed986bec-4f28-11e4-8db4-6277d01a0e48.png)

**Comment by matthewdean** [comment]
I'm going to close this since it's not reproducible (the odds of this happening again are low)
