### ISSUE TITLE
"Play in App" Doesn't launch App/Game.

### ISSUE THREAD

**Issue by manofarmy12** [Anaminus/roblox-bug-tracker#487]
I'm using iOS 8.0.2, 5th generation iPod.
Not using the mobile website, but desktop version (so I can forum). But, if you wanted to play a game. You click the game you'd like to play, and it'll say "play in app". Once you click it. It doesn't launch the game/app.

**Comment by Squidcod** [comment]
Appears to be working now.
Probably just an old bug.
