### ISSUE TITLE
Objects reparented by explorer panel are temporarily moved to Workspace

### ISSUE THREAD

**Issue by Anaminus** [Anaminus/roblox-bug-tracker#499]
In the explorer panel, when dragging one or more objects to a new parent, they are first added to the Workspace. This does not occur for objects that are already descendants of the Workspace.

1. Insert a ScreenGui into StarterGui
2. Run the following command: `Game.StarterGui.ScreenGui.AncestryChanged:connect(print)`
3. Drag the ScreenGui into ServerStorage
4. Observe that the ScreenGui was first moved to the Workspace:
```
ScreenGui Workspace
ScreenGui ServerStorage
```

**Comment by matthewdean** [comment]
Fixed by [twberg](http://www.roblox.com/User.aspx?ID=33067469).
