### ISSUE TITLE
Stock sounds getting duplicated

### ISSUE THREAD

**Issue by matthewdean** [Anaminus/roblox-bug-tracker#514]
Every time you open a place in studio, more stock sounds are added to Soundscape. So after a while it looks like this:

![image](https://cloud.githubusercontent.com/assets/4099467/4877902/deb5c71a-62fa-11e4-8a93-867d65c19db5.png)

Reproduction steps
1. Open a new place file
2. Save the place
3. Close and re-open the place
4. Observe that Soundscape now has lots of unecessary sounds

**Comment by matthewdean** [comment]
It appears that the sounds aren't parented to SoundService anymore, so this is a non-issue. Re-open if I am wrong.

**Comment by Anaminus** [comment]
Indeed isn't an issue anymore. According to the [Change Log](http://wiki.roblox.com/index.php?title=Change_log):

> 8 January 2014 - Studio - Newly created places no longer add stock sounds under SoundService.
