### ISSUE TITLE
Motor6D instances warping/shrinking/bending parts

### ISSUE THREAD

**Issue by claylittlehorse** [Anaminus/roblox-bug-tracker#518]
If you run this CFrame on a Motor6D instance about 10 times, it starts to visibly warp the Part1 of the motor: `Motor.C1 = Motor.C0:inverse() * Motor.Part0.CFrame:inverse() * Motor.Part1.CFrame * Motor.C1`

After running the code 16 times, the part is spaghettified into nonexistence and no longer visible at all. Any 3D GUI element will warp with the part, like ArcHandles, SelectionBoxes, etc.

I believe this code is causing an exponential increase in the rotation matrix of the motor, which in turn begins to warp the part.

**Comment by Juddily** [comment]
Yes, exactly!
