### ISSUE TITLE
Crash when dividing two Vector3int16s

### ISSUE THREAD

**Issue by matthewdean** [Anaminus/roblox-bug-tracker#525]
The following code will crash the ROBLOX engine:
```lua
print(Vector3int16.new() / Vector3int16.new())
```

**Comment by matthewdean** [comment]
print(Vector3int16.new() / Vector3int16.new())
--> Divide by zero exception

**Comment by The0neThe0nly** [comment]
Proper checks have been implemented. Fixed for Vector2int16 as well.
