### ISSUE TITLE
New layout disables / refreshes your page on the catalog when trying to change the page number.

### ISSUE THREAD

**Issue by chrisrblx** [Anaminus/roblox-bug-tracker#528]
![image](https://cloud.githubusercontent.com/assets/8672692/5273752/76dc3824-7a59-11e4-9079-753e81691ea6.png)

Now lets change the number.
![image](https://cloud.githubusercontent.com/assets/8672692/5273758/84975778-7a59-11e4-90fe-e9291fe40852.png)

Redirect occurs.
![image](https://cloud.githubusercontent.com/assets/8672692/5273761/952341c4-7a59-11e4-83cb-45fc22043e4b.png)
[picture one and picture three are two different photos. i did not refresh my computer. if this helps: im using google chrome and im not using any ROBLOX related chrome plugins.]

**Comment by matthewdean** [comment]
Was fixed.
