### ISSUE TITLE
Scriptable Camera can't be easily used with physics parts (relates to issue #256)

### ISSUE THREAD

**Issue by kyle-emmerich** [Anaminus/roblox-bug-tracker#532]
Since we have no way to get the actual *rendered* position of a part, we can't really attach cameras to parts that move via ROBLOX physics rigidly. This is a huge problem for games that require the camera to be attached to a part that may roll.

My best suggestion for an immediate fix would be to let CameraSubject matter to a Scriptable type camera, essentially. Let CoordinateFrame be an offset from the CameraSubject's CFrame. This is mostly consistent with existing behavior. A better fix would be to restructure the Camera entirely. It's a terrible relic of old Roblox and while it *works*, it's only *just* working. It holds back future progress.

**Comment by matthewdean** [comment]
There is now a way to get the rendered CFrame of a part: `BasePart:GetRenderCFrame()`. If this is still an issue, please comment with more information.
