### ISSUE TITLE
The new ROBLOX Home page does not cooperate with different screen sizes.

### ISSUE THREAD

**Issue by chrisrblx** [Anaminus/roblox-bug-tracker#535]
![image](https://cloud.githubusercontent.com/assets/8672692/5480522/fe965f58-8614-11e4-8f5a-3248e54fd792.png)

Where I cut it off is where the home page starts for me.

**Comment by tobyteel** [comment]
This appears to be mostly fixed now for me.  There are a few pixels of overlap with the ad (maybe 10-20px, had to emulate screen size, so it's hard to get exact), but it's not nearly as bad as your screen shot.  Should we keep this open, or just close it?

**Comment by Anaminus** [comment]
Nothing important is getting cut off, so I'd say that it's fixed.
