### ISSUE TITLE
Refresh on Games tab does not refresh VIP servers.

### ISSUE THREAD

**Issue by Slappy826** [Anaminus/roblox-bug-tracker#537]
If you are invited to a VIP server and want to see whos on without joining you have to manually refresh the page each time as the refresh button at the bottom does not refresh VIP servers.

**Comment by samfun123** [comment]
There is a (hacky) way to refresh the VIP servers. If you click another tab like Recommendations or Commentary and then switch back it will have refreshed the VIP servers

**Comment by samfun123** [comment]
This has been fixed.

![viprefresh](https://cloud.githubusercontent.com/assets/6759716/5793228/3097b246-9f0a-11e4-8071-a0c52500e2c8.PNG)
