### ISSUE TITLE
ScrollingFrames do not release scrollbar when mouse button is released over a GuiButton

### ISSUE THREAD

**Issue by Defaultio** [Anaminus/roblox-bug-tracker#539]
If the mouse is dragging the scrollbar of a Scrolling frame, it is normal behavior for the mouse to be able to leave the scrollbar with the left mouse button held down and still be able to move the scrolling frame. However, if the mouse lands on a GuiButton and releases the left mouse button while over it, the scroll bar will not be released from the mouse, regardless of any subsequent clicking. It can only be fixed by going back to the scroll bar and clicking on it. This only happens if the ZIndex of the GuiButton is at least the ZIndex of the ScrollingFrame.

![image](http://i.imgur.com/r68le6C.gif)

**Comment by RobloxCodeWriter** [comment]
Should be fixed now.

**Comment by Anaminus** [comment]
Confirmed to be fixed.
