### ISSUE TITLE
Gamepasses show the purchase info for buying a VIP server

### ISSUE THREAD

**Issue by samfun123** [Anaminus/roblox-bug-tracker#540]
![capture](https://cloud.githubusercontent.com/assets/6759716/5555582/52986578-8c83-11e4-9e93-f1d7fa4c4423.PNG)

**Comment by matthewdean** [comment]
Since the message about VIP servers being in beta has vanished, this is no longer an issue
![image](https://cloud.githubusercontent.com/assets/4099467/5832592/219a012c-a10d-11e4-96d8-3e78734ce564.png)
