### ISSUE TITLE
The following hat's 3D view has a black texture.

### ISSUE THREAD

**Issue by chrisrblx** [Anaminus/roblox-bug-tracker#543]
http://www.roblox.com/Theodorian-the-Third-item?id=81708799

![image](https://cloud.githubusercontent.com/assets/8672692/5594042/9e2240e2-9203-11e4-9d25-7e2cc4a248f0.png)

![image](https://cloud.githubusercontent.com/assets/8672692/5594044/a719957e-9203-11e4-859a-72f5509a09d4.png)

**Comment by Anaminus** [comment]
Please use the [asset tracker](https://github.com/matthewdean/roblox-asset-bug-tracker/issues) for issues related to ROBLOX assets.
