### ISSUE TITLE
Unable to record video in Studio Play mode

### ISSUE THREAD

**Issue by SSonic70** [Anaminus/roblox-bug-tracker#545]
In Studio, if you use the play solo feature and try to record a video, the record button goes to the clicked state, but ROBLOX does not record the game, making the record video button have no function.

Reproduction steps:
1. Open a place in ROBLOX Studio
2. Use the Play testing mode to run your place in testing mode.
3. Hit the record button.
4. ROBLOX doesn't record, but the record video button is in the clicked state.

**Comment by Anaminus** [comment]
This appears to be core script problem, so this should be posted on the [Core-Scripts](https://github.com/ROBLOX/Core-Scripts) issue tracker.
