### ISSUE TITLE
Event Mouse.KeyDown does not fire for the digit keys (1,2,3,4,5,6,7,8,9,0)

### ISSUE THREAD

**Issue by frederikam** [Anaminus/roblox-bug-tracker#549]
Event Mouse.KeyDown does not fire for the digit keys. This applies to both the numpad and the keys lined just below the function (f1, f2 etc) keys. These keys are expected to fire with KeyDown, as they do fire with KeyUp like most other keys.
I tested this with both the Danish Windows layout and the US Windows keyboard layout (on Windows), and this bug seems to apply to both layouts. This was tested only in studio mode.
This bug can be reproduced with this **LocalScript**:
```lua
game.Players.LocalPlayer:GetMouse().KeyDown:connect(function(key)
	print(tostring(key).." is down.")
end)
game.Players.LocalPlayer:GetMouse().KeyUp:connect(function(key)
	print(tostring(key).." is up.")
end)
```
I will be grateful for a fix on this :)
-frederikam

**Comment by Gskartwii** [comment]
I wonder if those are only meant for tool hotkeys, but I'm not sure if that's true or not.

**Comment by frederikam** [comment]
I don't see why they'd bother disabling these keys for KeyDown. Especially considering that KeyUp works with these keys.

**Comment by Anaminus** [comment]
This happens because the keys are occupied by the Backpack core script. They should work if you disable the backpack:

```lua
game.StarterGui:SetCoreGuiEnabled(Enum.CoreGuiType.Backpack, false)
```

If they still don't work after that, then submit an issue on the [Core-Scripts](https://github.com/ROBLOX/Core-Scripts) issue tracker.
