### ISSUE TITLE
Search for exact game name returns different ones for no reason, wrong SQL query?!

### ISSUE THREAD

**Issue by DaviCavalc** [Anaminus/roblox-bug-tracker#550]
Searching for the exact name of place id 21363989 (Build a Mini Country Earth Edition), for example, returns different games like "Kingdoms of Vorlong" "GTA V: ONLINE" "Build to survive 9007" "Urban Patrol 2.0", etc.

[I see a wrong SQL query in this?](http://i.imgur.com/bRaEEZs.png)

**Comment by matthewdean** [comment]
Fixed by RoboxSai
