### ISSUE TITLE
:MoveTo() isn't cooperating with humanoids.

### ISSUE THREAD

**Issue by TheTalentedHero** [Anaminus/roblox-bug-tracker#551]
MoveTo isn't moving correctly when I call it using the pathfinding example ROBLOX used in the tutorial. I don't know if it doesn't work only in the script I am using.

**Comment by SNCPlay42** [comment]
>isn't moving correctly

Please be more specific.

**Comment by Anaminus** [comment]
Please make sure you read through the [README](https://github.com/Anaminus/roblox-bug-tracker#things) before submitting issues. In this case, there isn't enough information to determine whether this is a problem with Roblox, or just your script.

**Comment by TheTalentedHero** [comment]
My bad... I was tired :|
