### ISSUE TITLE
Setting a place as the start place of a universe fails

### ISSUE THREAD

**Issue by Thewsomeguy** [Anaminus/roblox-bug-tracker#554]
When I try to set any place as the start place of a universe, I get "Error Occurred"

It seems that /universes/setrootplace returns "{success:false,message:Error Occurred}", and then another request to the same file (right after the call that returned false success..) returns "{success:true}". but the start place is still not set.

**Comment by matthewdean** [comment]
Can you verify that this still occurs? Raeglyn says the bug is being fixed today.

**Comment by Thewsomeguy** [comment]
This is still occurring. When I changed the settings of my universe to enable studio API access (for datastore editing), it removed my start place, so I can't make my place active now (it showed it as active, but on the game's page, it said it was closed to visitors)

**Comment by Thewsomeguy** [comment]
This has been fixed as far as I can tell.
