### ISSUE TITLE
Sound.TimePosition and Sound.TimeLength don't work at all

### ISSUE THREAD

**Issue by GigsD4X** [Anaminus/roblox-bug-tracker#555]
It seems like Sound.TimePosition and Sound.TimeLength are always 0, regardless of whether you check server-side or client-side.

Also, setting Sound.TimePosition doesn't do anything (the wiki says it should set the current time marker to the given seconds) :(

**Comment by Thewsomeguy** [comment]
They disabled those properties over a week ago according to the change log.
http://wiki.roblox.com/index.php?title=Change_log

**Comment by Anaminus** [comment]
Yes, these features have been disabled until a few related issues are fixed.

**Comment by TheSneak** [comment]
Is this supposed to have been turned back on in last night's update? I'm still experiencing issues with TimeLength. I can get TimeLength to work (with some finessing) in studio on the server, but online, it doesn't work.

**Comment by zeux** [comment]
TimeLength should have been fixed, I think. Can somebody confirm?

**Comment by TheSneak** [comment]
local Create = LoadLibrary("RbxUtility").Create
    local sound = Create"Sound"{
    	Name = "LeroyJenkins",
    	Parent = game.ReplicatedStorage,
    	SoundId = "http://www.roblox.com/asset/?id=130758889"
    }
    print(sound.TimeLength)
    wait(1)
    print(sound.TimeLength)

When this script is run from a server script, the output is 

    0
    0

When run from a client script the output is 

    0
    4.284

TimeLength does not work at all in server scripts and only works in client scripts after a delay.

**Comment by hockeychaos** [comment]
This is working as expected.  Servers don't actually load any sounds since
there is no one to listen.  Clients obviously load them, and it can't get
the length until the sound is finished loading. We could add a Loaded event
to sounds, so you can get the length without the need for an arbitrary wait.

On Tue, Apr 14, 2015 at 10:41 AM, TheSneak <notifications@github.com> wrote:

> local Create = LoadLibrary("RbxUtility").Create
> local sound = Create"Sound"{
>     Name = "LeroyJenkins",
>     Parent = game.ReplicatedStorage,
>     SoundId = "http://www.roblox.com/asset/?id=130758889"
> }
> print(sound.TimeLength)
> wait(1)
> print(sound.TimeLength)
>
> When this script is run from a server script, the output is
>
> 0
> 0
>
> When run from a client script the output is
>
> 0
> 4.284
>
> TimeLength does not work at all in server scripts and only works in client
> scripts after a delay.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaminus/roblox-bug-tracker/issues/555#issuecomment-92992696>
> .
>



-- 
ben

**Comment by hockeychaos** [comment]
You can already get the timelength by listening to the changed event on a
sound however now that I think about it.

sound.Changed:connect(function(prop) if prop == "TimeLength" then
print("length is now",sound.TimeLength) end end)

On Tue, Apr 14, 2015 at 10:41 AM, TheSneak <notifications@github.com> wrote:

> local Create = LoadLibrary("RbxUtility").Create
> local sound = Create"Sound"{
>     Name = "LeroyJenkins",
>     Parent = game.ReplicatedStorage,
>     SoundId = "http://www.roblox.com/asset/?id=130758889"
> }
> print(sound.TimeLength)
> wait(1)
> print(sound.TimeLength)
>
> When this script is run from a server script, the output is
>
> 0
> 0
>
> When run from a client script the output is
>
> 0
> 4.284
>
> TimeLength does not work at all in server scripts and only works in client
> scripts after a delay.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaminus/roblox-bug-tracker/issues/555#issuecomment-92992696>
> .
>



-- 
ben

**Comment by TheSneak** [comment]
Are you sure the TimeLength property causes a Changed event to fire? Not all property changes do, and my tests with that property are unsuccessful.

**Comment by hockeychaos** [comment]
Yeah, just looked at the code, looks like it won't right now.... I'll see
if I can fix that.

On Tue, Apr 14, 2015 at 11:12 AM, TheSneak <notifications@github.com> wrote:

> Are you sure the TimeLength property causes a Changed event to fire? Not
> all property changes do, and my tests with that property are unsuccessful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaminus/roblox-bug-tracker/issues/555#issuecomment-93004600>
> .
>



-- 
ben

**Comment by TheSneak** [comment]
Is it reasonable to request that the TimePosition property also fires a Changed event when it changes? It doesn't appear to do so currently.

**Comment by TheSneak** [comment]
On a related note, the PlayCount property DOES fire a Changed event when changed, but that property is not readable so code like this fails when :Play() is executed.

    sound.Changed:connect(function(prop)
	    print("prop", prop, sound[prop])
    end)

**Comment by hockeychaos** [comment]
I just added this, should see it in about a week or so.

On Tue, Apr 14, 2015 at 11:19 AM, TheSneak <notifications@github.com> wrote:

> Is it reasonable to request that the TimePosition property also fires a
> Changed event when it changes? It doesn't appear to do so currently.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaminus/roblox-bug-tracker/issues/555#issuecomment-93006530>
> .
>



-- 
ben

**Comment by TheSneak** [comment]
I just tested this in the newly updated Studio. Following are my results
* Changed isn't fired for changes to the property TimePosition
* Changed is fired for TimeLength each time the sound is played even if the length did not change.
* PlayCount is still not readable 

Only the first point is of much significance to me. I would like to be able to stop playing a sound after x milliseconds without resorting to a wait loop. It's great that the TimeLength changes are broadcast.

**Comment by Anaminus** [comment]
@TheSneak

- Changed cannot be fired for TimePosition because the audio is constantly streaming. It would have to be fired at some sort of increment, and there's no reasonable frequency at which to do this. If you really need it, you can request a callback feature, which would work much better.
- TimeLength should only fire the Changed event if it changes. This should be submitted as a separate issue.
- PlayCount is not meant to be readable. It is apart of a larger problem of unscriptable properties being exposed by the Changed event.

**Comment by Anaminus** [comment]
TimeLength and TimePosition now appear to work as expected.
