### ISSUE TITLE
Event Sound.Ended should exist

### ISSUE THREAD

**Issue by GigsD4X** [Anaminus/roblox-bug-tracker#556]
There is literally __no way__ to tell when a sound has finished playing. However, it seems physically possible, since Sound.DidLoop fires when the sound has finished playing and is about to start over again). We've gotta have a `Sound.Ended` event.

Also, Sound.IsPlaying doesn't update when the sound finishes playing.

**Comment by Thewsomeguy** [comment]
What about the `Stopped` event?

**Comment by Anaminus** [comment]
Yeah, this is likely what the Stopped event does (or will do once it's enabled).
