### ISSUE TITLE
Function to get list of players in team

### ISSUE THREAD

**Issue by Phalanxia** [Anaminus/roblox-bug-tracker#558]
There should probably be a function under the team class which returns a list of players within the team

**Comment by matthewdean** [comment]
I think there are more important things to be implemented, especially considering this can be accomplished with 9 lines of Lua:
```lua
function getPlayers(team)
  local players = {}
  for _, player in pairs(game:GetService("Players"):GetPlayers()) do
    if player.TeamColor == team.TeamColor then
      table.insert(players, player)
    end
  end
  return players
end
```

**Comment by CoffeeFlux** [comment]
Yeah, i'm of the same opinion as @matthewdean
