### ISSUE TITLE
Players:GetPlayerFromCharacter(nil) should return nil

### ISSUE THREAD

**Issue by matthewdean** [Anaminus/roblox-bug-tracker#560]
Instead it returns the first player whose Character property is set to nil. This means if you write code like this:

```lua
part.Touched:connect(function(hit)
  local player = game.Players:GetPlayerFromCharacter(hit.Parent)
end)
```

And the hit's Parent was nil (e.g. a script destroys the hit part) then you could potentially get a player when you shouldn't.

**Comment by zeux** [comment]
Should be fixed on desktop (iOS will follow in ~1 week as usual)
