### ISSUE TITLE
Clicking the "next" arrow for gamepasses, doesn't show next page.

### ISSUE THREAD

**Issue by manofarmy12** [Anaminus/roblox-bug-tracker#565]
I've recently in-countered a ROBLOX website bug that deals with the "Passes For This Game" tab. In Games.
If there are 2 (or more) pages of gamepasses and you click the "next" arrow, it'll show the first gamepasses shown on the "Page 1 of 2"

This bug re-occurs to every ROBLOX game that sells 2 or more pages of gamepasses.

I do have a video on what this bug looks like.

VIDEO - https://www.youtube.com/watch?v=vlKd09ZM7AI

How to occur this bug.

Step 1:
Go to any game that sells gamepasses on the games page.
2: scroll down until you see the "Passes For This Game" area.
3: Make sure that the game sells 2 or more pages of gamepasses.
4: Click the "next" arrow.
5: See that the next page has the same passes for the first page.

Thank you for your time.
Reported by user - IronSight1x1

**Comment by matthewdean** [comment]
No longer occurs because that area of the website was revamped.
