### ISSUE TITLE
RequestFriendship/RevokeFriendship Error Typo

### ISSUE THREAD

**Issue by The0neThe0nly** [Anaminus/roblox-bug-tracker#566]
By setting the player argument in RequestFriendship to something that is not a player, an error shows.

![error_msg](http://puu.sh/fVilH/21d29a1fe7.png)

This error text should be changed.

**Comment by Anaminus** [comment]
It's technically correct, but unconventional. It's saying "a Player should be passed to RequestFriendship", but with "RequestFriendship" first.
Regardless, it should really just say something like "first argument to RequestFriendship must be a Player".

**Comment by The0neThe0nly** [comment]
This also applies to RevokeFriendship.
