### ISSUE TITLE
Boundries?

### ISSUE THREAD

**Issue by XerontWolfe** [Anaminus/roblox-bug-tracker#568]
My place has some type of boundries, whenever I move models, or insert them, past a specific point, it breaks and merges and teleports to other areas. What is going on??

**Comment by samfun123** [comment]
Could you provide some kind of video/gif showing the problem?

**Comment by XerontWolfe** [comment]
No idea how, sorry. but when I drag it, all the stuff merges to the center, or hits an invisible wall and refences to go any further unless dragged by an arrow.

**Comment by Anaminus** [comment]
There is not enough information to reproduce the problem. Please view the [README](https://github.com/Anaminus/roblox-bug-tracker) before submitting issues.
