### ISSUE TITLE
Better censorship in TextBoxes and other GuiObjects

### ISSUE THREAD

**Issue by SFOH** [Anaminus/roblox-bug-tracker#569]
In any text related Gui object, you can type in a censored word (according to diagones.fnt) plus another random letter (even letters that won't display in a textbox such as À) and it will go through just fine. This is a problem as I want to create a custom chat GUI but I also do not want players to have the ability to say profane things in the chat.

**Comment by Anaminus** [comment]
There is already a solution to this. Before displaying text that was written by one player to another player, run that text through [Chat.FilterStringForPlayerAsync](http://wiki.roblox.com/index.php?title=FilterStringForPlayerAsync). While the player who wrote the text will see it unfiltered, it will be filtered for others.
