### ISSUE TITLE
Uploading decal bug

### ISSUE THREAD

**Issue by Aquilapath** [Anaminus/roblox-bug-tracker#570]
When you go inside the develop tab and try to upload a image as a decal it will say,

"Upload failed. Make sure what you're uploading is an image."

I tried to upload several png's and all of them were rejected, I as tried to re upload a png and it rejected it.

Bug on Google Chrome.

How to replicate,

1. Go to Develop
2. Select Decals
3. Select any png image
4. Click upload

**Comment by matthewdean** [comment]
This is probably due to the recent maintenance. Does it still happen?

**Comment by matthewdean** [comment]
I'm going to assume this is fixed.
