### ISSUE TITLE
Cannot copy/paste script code in studio

### ISSUE THREAD

**Issue by rbxJet** [Anaminus/roblox-bug-tracker#571]

**Comment by SFOH** [comment]
I'm having this problem as well. It works fine when you boot up, but after a while it just stops working.

**Comment by rbxJet** [comment]
I believe this bug only occurs within the latest version of ROBLOX Studio.

**Comment by Anaminus** [comment]
Please view the [README](https://github.com/Anaminus/roblox-bug-tracker#roblox-bug-tracker) before submitting issues.
