### ISSUE TITLE
Trying to load your character up in 3D does not work.

### ISSUE THREAD

**Issue by Clewbie** [Anaminus/roblox-bug-tracker#573]
I have a problem with the 3D character, when I try to load my character up on the profile or character page, it just shows "Loading" forever.

If I could get some help, that would be really appreciated.

Currently using Internet Explorer 11, Windows 8.1.

**Comment by einsteinK** [comment]
If you have Google Chrome, try using that for once.
If it does work there, we're sure it has to do with IE 11.
(If it doesn't, you can rightclick the webpage, select Inspect Element > Console for possible error logs)

**Comment by JanBerktold** [comment]
Cannot replicate with the same machine setup.

**Comment by Anaminus** [comment]
Going to assume that the issue is fixed. Provide reproduction steps if this is not the case.
