### ISSUE TITLE
Models appear to be in world space in a different position than other players

### ISSUE THREAD

**Issue by JasonTheOwner** [Anaminus/roblox-bug-tracker#574]
Issue: Player A  spawns a model, imported from server storage using a combination of client/server events and will NOT see the model at the position Player B sees it, collides with it, etc, thus models spawned by Player A, it appears to Player A that player B is walking thru his model, but when Player B stands on top of it, it appears to Player A that he is floating in mid-air.  

This is occurring not only with my own newly scripted place, but in Base Wars, where players are seemingly going thru the walls of the bases, but from their own perspective, everything is normal - they are NOT going thru walls.  This started occurring as early as March 1, within Base Wars.

My own scripted game uses filtering enabled and client/server events to facilitate the spawning of models which are CFramed 4 studs in front of the player after selected from a GUI.

**Comment by einsteinK** [comment]
Do you mean:
- The server puts a model in ReplicatedStorage (or any other replicated object)
- The client puts it in Workspace (and moves it around maybe)

If that's the case, that's sort of normal.
If you want something to be positioned at the same spot on all clients, let the server control it.
Use Start Server + 2x Start Player and try to replicate the bug.
If it happens, you'll probably see they are "different", and not visible on the server.
(On the server you just have the one model in the ReplicatedStorage)

**Comment by JasonTheOwner** [comment]
I have filtering enabled turned on so only the server can place the object, but I'll try this suggestion.

I'm noticing in another game, base wars by d8dev, that players seem to be able to walk around their base normally, but to other players it looks like they are going thru the walls, and he hasn't updated his code, so it appears to be a bug from a roblox update.  I can't imagine so many players having hacking abilities to do this.

**Comment by JasonTheOwner** [comment]
OK, I tested with two clients with my local Studio, all appears normal.  I'll test with the user who was having issues, yesterday, and see if this issue persists since last nights Roblox update.
