### ISSUE TITLE
HyperBike can go through parts

### ISSUE THREAD

**Issue by 3ZD** [Anaminus/roblox-bug-tracker#579]
![image](https://cloud.githubusercontent.com/assets/9162370/6764919/cf805d00-cfbf-11e4-8e1c-bf3aab9f6aa1.png)
As you can see i can go right through parts using the hyperbike
by equiping and dequiping plus jumping all at the same time.

**Comment by Anaminus** [comment]
Please use the [asset tracker](https://github.com/matthewdean/roblox-asset-bug-tracker/issues) for bugs related to gear.

**Comment by 3ZD** [comment]
why did you close it?
