### ISSUE TITLE
ImageLabel crashing when trying to upload image

### ISSUE THREAD

**Issue by ArmoredReaper** [Anaminus/roblox-bug-tracker#581]
As the title says, I'm getting ROBLOX Studio to crash every time I try to upload an image using an ImageLabel Instance. The little window opens when I click Image, but once I search the image and try to upload it, ROBLOX Studio just freezes for some seconds, and then crashes.

MacBook Pro 13" Mid-2012 w/o Retina Display
OS X Yosemite 10.10.2
ROBLOX Studio v0.189.0.57585

**Comment by samfun123** [comment]
Duplicated of #578
