### ISSUE TITLE
ROBLOX Studio becomes non functional till you reload the page

### ISSUE THREAD

**Issue by Lithi3m** [Anaminus/roblox-bug-tracker#584]
*Report*:
The ROBLOX Studio freezes at a random time till you reload the page.

*Cause*:
The studio is not capable to control the amount of request it receives, so it freezes the system.

*Solution*:
Higher the capacity of the internal servers.

**Comment by gamenew09** [comment]
I would actually think that is your computer not being able to handle requests.

**Comment by Lithi3m** [comment]
Oh alright, I'll consider that.

**Comment by Lithi3m** [comment]
No, like the page freezes, not my computer. My computer keep working prefectly fine when that happens.
