### ISSUE TITLE
Add 'Packages' to the Favorites Category

### ISSUE THREAD

**Issue by McFallon** [Anaminus/roblox-bug-tracker#591]
Repro steps:

1) Go the ROBLOX catalog (www.roblox.com/catalog)
2) Select 'Clothing'
3) Select 'Packages'
4) Click on any package
5) Favorite it
6) Go to your ROBLOX profile

What happens:
The package you chose as a favorite doesn't appear under your favorites on your profile simply because the category for 'packages' is missing.

What needs to happen:
The package needs to appear under the appropriate category, just like any other item from the catalog you can add as a favorite.

**Comment by Squidcod** [comment]
Not a Bug.
