### ISSUE TITLE
Saving string to DataStore won't work

### ISSUE THREAD

**Issue by SFOH** [Anaminus/roblox-bug-tracker#597]
When I try saving a string to a DataStore, it will tell me that "Data contains objects that can't be stored".

The string : "fbfb#fgggfffffffffff"

local DataStoreService = game:GetService("DataStoreService")
local DataStore = DataStoreService:GetDataStore("PlayerDataStorage12")
DataStore:SetAsync("user_"..userId,"fbfb#fgggfffffffffff")

where userId is a player's userId

**Comment by matthewdean** [comment]
Please provide code which reproduces the issue. The code you provided runs successfully and causes no errors. It's likely that this is a bug in your scripts and not ROBLOX.
