### ISSUE TITLE
The Shiny and Specular properties in Textures and Decals don't do anything.

### ISSUE THREAD

**Issue by Anaminus** [Anaminus/roblox-bug-tracker#6]

**Comment by The0neThe0nly** [comment]
Although Shiny and Specular do not seem to do anything visibly, I looked at both of the properties internally and they seem to have code attached to them that regulate what can be set. For example, Shiny cannot be set below zero.

**Comment by Anaminus** [comment]
They used to work way way back, but their implementation was probably neglected when the shader system was updated.

**Comment by matthewdean** [comment]
These two properties have been deprecated.
