### ISSUE TITLE
InsertService won't allow inserting models with unions you don't own.

### ISSUE THREAD

**Issue by SFOH** [Anaminus/roblox-bug-tracker#601]
game:GetService("InsertService"):LoadAsset(237429713)

>>403 asset is not approved for this place

Uses unions I don't own but received from my friend Dogon.

**Comment by samfun123** [comment]
Let me guess this straight you own the model but there is unions in the model that are uploaded that you don't own

**Comment by SFOH** [comment]
Yes - Dogon sent me the union. I do not understand why exactly I am having trouble inserting this model - free models have user-created unions in them all the time. I even tried making it a "free" model. Needless to say, it did not work.

**Comment by matthewdean** [comment]
Does this bug still happen?
