### ISSUE TITLE
Some groups dosent even appear on the group search.

### ISSUE THREAD

**Issue by UnionistsRBLX** [Anaminus/roblox-bug-tracker#602]
Some groups dose not even appear on the group search page even though it has like 100+ members.

Take my group for example, http://www.roblox.com/My/Groups.aspx?gid=2561642. My groups has 109 members (when it was published)

Search the word 'Singapore'. It dose not show up.

I think it is a glitch or something. This is really crucial for groups.

**Comment by Anaminus** [comment]
I suspect that newer groups are excluded from the search. It may be added eventually.

**Comment by matthewdean** [comment]
Should be fixed. Group searching was significantly improved within the past few days. I just made a new group and found it by searching within seconds.
