### ISSUE TITLE
Tool.Equipped event no longer fired

### ISSUE THREAD

**Issue by TheSneak** [Anaminus/roblox-bug-tracker#603]
The Tool.Equipped event is no longer fired when the tool is equipped.

Steps to reproduce:

* Start a new place
* Add a tool to StarterPack
* Add a LocalScript to the tool
* Insert the following code into the LocalScript
```
    print("TOOL LOCAL SCRIPT:", script.Parent.Name)
    local tool = script.Parent
    tool.Equipped:connect(function()
        print("Equipped LOCAL", script.Parent.Name)
    end)
    print("DONE RUN LOCAL SCRIPT")
```
* Press F6 to run
* Press 1 to equip the tool
* The message in the Equipped handler is not printed

**Comment by Anaminus** [comment]
Tools need a BasePart named "Handle" as a child in order to for them to equip.
