### ISSUE TITLE
Failing To Show Profile Page Of Person [Through The Use Of Group Admin, Members Section]

### ISSUE THREAD

**Issue by MrJimenex** [Anaminus/roblox-bug-tracker#604]
When In Group Admin, Members Section, say you want to view a person's profile by clicking the username, that is meant to direct you to their profile page, comes up with an error. The people's profiles that I clicked are not banned or suspended, as I tried it without using it there, and worked.

![image](https://cloud.githubusercontent.com/assets/11672576/7173262/f751decc-e3b9-11e4-9f0c-c50012ccb8f9.png)

![image](https://cloud.githubusercontent.com/assets/11672576/7173281/4eb0d60a-e3ba-11e4-8375-94970a8f4a00.png)

**Comment by MrJimenex** [comment]
Let's say I wanted to fix this bug, or any possible bug, do you have any way of learning code, or a specified code that works with this site, because I would really like to help staff out.

**Comment by Thewsomeguy** [comment]
More info on this bug:

It appears that it's just an invalid url. Here's a snippet of the html:

`<a class="notranslate" href="~/User.aspx?ID=74913756" title="pizzaboy243">pizzaboy243</a>`

When you click this link, it takes you to `http://www.roblox.com/My/~/User.aspx?ID=74913756`, which doesn't exist. Without the ~, it's a valid url.

**Comment by tobyteel** [comment]
This has been fixed.
