### ISSUE TITLE
ROBLOX Studio selection cursor missing (update has fixed this)

### ISSUE THREAD

**Issue by bubbaman73** [Anaminus/roblox-bug-tracker#608]
So i THINK it had something to do with the Particle Emitter update for starters. But the problem is, when i hover over something like a model, brick, etc. i can move it and select it, but the selection cursor doesnt appear, (like the hand with the pointer finger) it stays at the pointed one. It also doesnt appear when im dragging an item.

**Comment by MrJimenex** [comment]
I saw that problem yesterday, but they released a new update today, and the different cursors were back in place, try checking again and see if the cursors returned.

**Comment by bubbaman73** [comment]
it is fixed :) thanksQ

**Comment by MrJimenex** [comment]
No problem
