### ISSUE TITLE
Add Hex Code Compability | Enhancement

### ISSUE THREAD

**Issue by MrJimenex** [Anaminus/roblox-bug-tracker#609]
This might rarely come in an occasion, but it would be good if ROBLOX Studio gave you the ability to choose whichever color you wanted, with the use of a Color ID #, 
![image](https://cloud.githubusercontent.com/assets/11672576/7331063/7b3c9d40-eac6-11e4-9407-04320b9b6a8d.png)

Similar to that of Twitter, which lets you choose your own color through the use of Color ID# as shown below.

![image](https://cloud.githubusercontent.com/assets/11672576/7331078/222deece-eac7-11e4-976b-a3eaeadca15e.png)

Custom color through the use of Color ID# can involve bricks, GUIs, whichever would have the ability to change the color of.

**Comment by Gskartwii** [comment]
They talked about this in the Developer Conference and they said that the colors are designed to work well together and allowing users to set the Color ID would result in weird-looking games.

**Comment by MrJimenex** [comment]
If developers choose not to use it, then they don't use it, but anyway it would be a good enhancement.

**Comment by Anaminus** [comment]
Are you saying that bricks should be able to be any color, or that the color picker should have an option to input a color in hexadecimal format? If it's both, then they need to be separate issues.
