### ISSUE TITLE
ROBLOX Uncopylocked Version Changer

### ISSUE THREAD

**Issue by HaywardMaster191** [Anaminus/roblox-bug-tracker#610]
What you need to do is use this link " http://www.Roblox.com/asset/?version=VERSION&id=ID "
Put it in a new Tab without Going to the link...
 http://www.Roblox.com/asset/?version=VERSION&id=ID
Change "VERSION" To the version number you want.
Change " ID " To the place ID
After that put the link in Your broser and then press enter..
From there it will download to your computer. 

If its been uncopylocked atleast once then anyone can still get it Resulting in Stealing of the place. 
If its not active and has been uncopylocked the result is the same.

This should be changed to better serve our games, As if someone "Famous " has had there place uncopylocked in the past then anyone can still there newer game and result in Downgrade of the games Popularity .

**Comment by MrJimenex** [comment]
Is this an issue?

**Comment by samfun123** [comment]
This isn't a problem because although you could use it to get the raw XML of assets you can only do this for assets that are uncopylocked.

**Comment by HaywardMaster191** [comment]
If its been uncopylocked atleast once then anyone can still get it Resulting in Stealing of the place. 
If its not active and has been uncopylocked the result is the same.

**Comment by matthewdean** [comment]
You can only download past versions of a place if the place is currently uncopylocked.

**Comment by HaywardMaster191** [comment]
No you can still get Past versions of a game that was once Uncopylocked. If its inactive and copylocked you can still get it.
