### ISSUE TITLE
Massive lag on web browsers when you browse on the ROBLOX website (Mac OS X)

### ISSUE THREAD

**Issue by PhoenixVortex** [Anaminus/roblox-bug-tracker#612]
Reporting Issue:
 I found out that ROBLOX.com constantly makes your computer (Mac OS X Users) lag, for about 5-10seconds. 

Why is this happening?
Roblox is a massive network which transfers and delivers content or upload it to your game client, it goes for one place to another, which is overloading the web browser, this applies to Safari, Firefox and chrome. Maybe all of the browsers that are available for the Mac Operating System.
Solution:
Roblox Studio works fine, but if you want to play games you have to restart your computer :( and log back in to ROBLOX, but you can also try disabling the flash and roblox launcher plugin/extension.

Conclusion:
Well, I am pretty sad because I've been experiencing this problem for about 3weeks.
I hope they can have a website which does NOT overload web browsers.

**Comment by MrJimenex** [comment]
What browser do you use in your Mac?

**Comment by PhoenixVortex** [comment]
I use all 3 browsers ( Firefox, Safari and Chrome) I tried the other browsers but there is still that constantly lagging problem.

**Comment by PhoenixVortex** [comment]
I hope they fix this problem.

**Comment by DaviCavalc** [comment]
Execute the command 'top' in your terminal with your browser open and pastebin the results.

**Comment by PhoenixVortex** [comment]
NEW SOLUTION! Google Chrome works perfectly now. Firefox is still having an
issue same as Safari, but Chrome works. Just reinstall Chrome and it should
work!

On Mon, May 18, 2015 at 12:15 AM, Davi Cavalcante Rocha <
notifications@github.com> wrote:

> Execute the command 'top' in your terminal with your browser open and
> pastebin the results.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaminus/roblox-bug-tracker/issues/612#issuecomment-102797802>
> .
>



-- 
Thanks,

Flamer_MW3
