### ISSUE TITLE
Roblox XML Place Files not saving NumberSequence or ColorSequence values

### ISSUE THREAD

**Issue by SheepGoesBaa** [Anaminus/roblox-bug-tracker#613]
All the ParticleEmitter properties that take a NumberSequence do not get saved in the XML format.

ColorSequence doesn't save in XML either

**Comment by Anaminus** [comment]
I've added a reproduction that shows the problem occurs when *loading* a file. The values in [particle.rbxmx](https://github.com/Anaminus/roblox-bug-tracker/blob/af3b1aea15ede74f1e4f2a2b8bbe0be2b6a3b6c3/issues/613/particle.rbxmx) show that they are saved properly.

**Comment by SheepGoesBaa** [comment]
Seems to be fixed.
