### ISSUE TITLE
RoleSets API does not get all ranks

### ISSUE THREAD

**Issue by FroastJ** [Anaminus/roblox-bug-tracker#614]
API: http://www.roblox.com/api/groups/{groupId}/RoleSets

The ROBLOX group API for getting RoleSets always misses one of the ranks.

Although it happens with all groups (I think), here's an easy example: http://www.roblox.com/api/groups/7/RoleSets

The "admin" role is missing from the table, even though it obviously exists:
http://www.roblox.com/Groups/group.aspx?gid=7

I created a workaround by using php to get RoleSets from the html of the group page. Nevertheless, this issue should be fixed.

**Comment by matthewdean** [comment]
This is a bug yes.

But I recommend using the the api.roblox.com group API (can be accessed in game via GroupService:GetGroupInfoAsync):

http://api.roblox.com/groups/7
```json
{
    "Name": "Roblox",
    "Id": 7,
    "Owner": {
        "Name": "ROBLOX",
        "Id": 1
    },
    "EmblemUrl": "http://www.roblox.com/asset/?id=13757480",
    "Description": "Official fan club!",
    "Roles": [{
        "Name": "Member",
        "Rank": 1
    }, {
        "Name": "Admin",
        "Rank": 254
    }, {
        "Name": "Owner",
        "Rank": 255
    }]
}
```

Unless you are trying to get the roleSetId.

**Comment by FroastJ** [comment]
Yes I am specifically trying to get the roleSetId, this is the only real ROBLOX API that includes it.

**Comment by FroastJ** [comment]
If support is dropped for this API it would be nice to add roleSetId to the other ones.

**Comment by FroastJ** [comment]
http://www.roblox.com/Services/GroupService.asmx/GetRoleSetsForGroup has same issue.

**Comment by einsteinK** [comment]
I checked both links:
http://www.roblox.com/api/groups/7/RoleSets
http://api.roblox.com/groups/7
I get all the ranks in both the APIs.

**Comment by FroastJ** [comment]
Fixed
