### ISSUE TITLE
UPDATE: all models with meshes that have a unapproved texture in the TextureId field display in thumbnail

### ISSUE THREAD

**Issue by NonstopEpic** [Anaminus/roblox-bug-tracker#615]
Update: I've been informed that the entire image system involving meshes and models is broken; any unapproved image that is used for a texture for a mesh or charactermesh in a model displays in the model thumbnail instead of being gray like it should until it is approved.

You can check below for the previous post.

This is a longly-written issue but it is kind of confusing if not properly explained, so I'll explain it here. When you upload a SpecialMesh that uses a texture you created (ex: retextures) as a model, if the texture has not been approved yet, the thumbnail of the model will be grey until the texture is approved and then it'll load the texture. This is a measure done so that inappropriate thumbnails can not be loaded through meshes as models. Thus, I was surprised to find that when you do a similar process on packages (package retexture for instance), the model thumbnail actually displays the unapproved textures.
For instance:
![image](https://cloud.githubusercontent.com/assets/9274929/7404267/35eedc4e-eeae-11e4-991a-0da4892e72fa.png)
Here is my model. It's a package with a new texture I made. At the time of writing the decal I uploaded and used for the model is still not approved; yet you can clearly see that the textures despite being unapproved load into the model thumbnail. What should be happening is that the model should be grey until the textures are actually approved.

The issue here is that people could abuse this to upload inappropriate decals as models. Here are some steps to reproduce if you want to try this out yourself:

1. Go on studio, and insert into workplace a properly set up humanoid model with a working CharacterMesh (this is how package meshes and textures are loaded).
2. Upload a decal to the ROBLOX site that is new, meaning it has not been approved before. (Review Pending)
3. Go back to studio. With your model, click on any CharacterMesh and change the OverlayTextureId to the ID of the image you uploaded (make sure it is the actual Image ID and not the decal ID)
4. Upload the model of the character with the modified package.
5. Check your models and see if the image actually loaded in the thumbnail.

**Comment by matthewdean** [comment]
Your conclusions aren't correct. Keep in mind that you can view images which you have uploaded before they are approved. To properly test this, make sure to log out, clear your WinINet cache, and then see if you can view the unapproved textures on a character mesh. You won't be able to.

**Comment by MrJimenex** [comment]
That happens with all ROBLOX assets, even though you can see them, others can't, until it is approved.
