### ISSUE TITLE
Camera broke for Right Click funcionality with Vehicle Seats on PC client

### ISSUE THREAD

**Issue by JasonTheOwner** [Anaminus/roblox-bug-tracker#616]
PC users report that when using vehicles, the right mouse button to move the camera to do a 3rd person view of the player, does not move the camera - the right mouse button function is completely disabled until the player leaves the vehicle.  Once a player leaves a vehicle, the normal 3rd person view resumes and right click functionality returns.  This bug is not noticeable until using vehicles.

This does not occur on the Mac client of Roblox.

**Comment by MrJimenex** [comment]
This needs some visual info.

**Comment by JasonTheOwner** [comment]
Ugh I thought of doing that...  the game Base wars is a perfect example where things are broke... I'll try to do some youtube video's tonight..

**Comment by JasonTheOwner** [comment]
Try the game Base Wars by D8Dev to get yourself a visual

**Comment by JasonTheOwner** [comment]
Nevermind its working - Roblox did two PC updates this evening which seemed to have resolved this issue, according to PC users in Base Wars at the time of this closing comment.
