### ISSUE TITLE
Add RGB Color Compability | Enhancement

### ISSUE THREAD

**Issue by MrJimenex** [Anaminus/roblox-bug-tracker#617]
I did a previous post about choosing your own color on Hex Code, Issue #609, but I was thinking of an enhancement that would use RGB Color Compability, instead of the traditional Hex Code, which is used in CSS, as it is used in services for example the Particle Emitter Service, or choosing a color for a TextBox, that sort of RGB, use any color based on three sections of digits, but not Hex Code.
![image](https://cloud.githubusercontent.com/assets/11672576/7528863/b6e9419e-f4f4-11e4-9b67-52201f17c216.png)

**Comment by einsteinK** [comment]
Isn't the Hex Code just a different formatting as the one we use?
Hex is, if I'm right: #RRGGBB with numbers being displayed as a 2-character hexadecimal string.
For the color (255,26,0) it would be #FF1A00
(As FF is 255, 1A is 26 and 00 is 0)

Basicly, you want to be able to use BrickColor.new(Color3 here) without it "clipping".
If you use BrickColor3.new(Color3.new(1,0,0)) it would return the BrickColor
that resembles your Color3 the most, which would be "Really red" in this case.
You just want it that when you give it C3(r,g,b), it stays that way.

Has been requested a lot, thought about a lot, and roblox is still thinking about it (probably).
Opening 20 issues about it won't help. You should've edited the previous issue to support Color3.
