### ISSUE TITLE
Changing character outfit twice results in error page.

### ISSUE THREAD

**Issue by Captain025** [Anaminus/roblox-bug-tracker#623]
I've noticed for a while that sometimes when I change my character's outfit and then change it again on the same page, I get moved to the error page, but it tends to have small chance of happening. (I use the Google Chrome browser.)
![image](https://cloud.githubusercontent.com/assets/9409518/7643850/3f679f0e-fa6b-11e4-8efb-ca1709d2adb3.png)

**Comment by samfun123** [comment]
Does only this happen when you change from an outfit and then back to the same one or will changing back to any outfit also cause the problem?

**Comment by Captain025** [comment]
It can happen when I change from one outfit to any other and then a different one from the first one.

**Comment by matthewdean** [comment]
Needs steps to reproduce the bug.

**Comment by samfun123** [comment]
I can't seem to reproduce this on the Chrome Browser. I tested it changing from one outfit to another and then back to the same outfit. I also tried it changing back to a different outfit from the first one and still couldn't reproduce it.
