### ISSUE TITLE
Clearing NetworkServer

### ISSUE THREAD

**Issue by supersonicfan111** [Anaminus/roblox-bug-tracker#624]
I was playing around on Script Builder, and noticed you could clear NetworkServer, causing a crash of the server, I used this code:
game:service'NetworkServer':ClearAllChildren()
I had inserted StringValues into NetworkServer (works with any object but ServerReplicators) earlier in the session, e.g:
Instance.new('IntValue', game:service'NetworkServer')
Run that code on script builder and it'll crash the server if anything BUT ServerReplicators are in NetworkServer, 
If you need video proof, I'd be glad to upload it.

I know it's to be expected, but ROBLOX should fix it.

**Comment by Anaminus** [comment]
Can you provide a place that reproduces this problem?

**Comment by samfun123** [comment]
As far as I can tell this problem has been fixed. I tested both of pieces of code provided in a test server in studio and neither caused the server to crash.
