### ISSUE TITLE
ROBLOX Icon in top-left corner is out of place

### ISSUE THREAD

**Issue by torpetopf** [Anaminus/roblox-bug-tracker#625]
![c9351c74311c77a66f2b34a9867d60ce](https://cloud.githubusercontent.com/assets/12542999/7746210/26c5f950-ffe3-11e4-9d07-f9ed60e0216b.png)
I was in incognito, and the ROBLOX logo was out of place ever since the last update. All extensions were disabled, but it was still out of place.

**Comment by MrJimenex** [comment]
I have no issue with that, and I have extensions enabled. This only involves some users, probably because of the screen dimension or such, but this is not happening with all ROBLOX users though.

**Comment by PhoenixVortex** [comment]
I found out that problem only happens with some users, but mainly it's
because something is wrong with your browser's resolution settings.

On Fri, May 22, 2015 at 1:02 PM, MrJimenex <notifications@github.com> wrote:

> I have no issue with that, and I have extensions enabled. This only
> involves some users, probably because of the screen dimension or such, but
> this is not happening with all ROBLOX users though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaminus/roblox-bug-tracker/issues/625#issuecomment-104464099>
> .
>



-- 
Thanks,

Flamer_MW3

**Comment by matthewdean** [comment]
I was able to repro this earlier today.

**Comment by Anaminus** [comment]
Seems like this is fixed.
