### ISSUE TITLE
Frequent read/write cycles on plugin save files crashes ROBLOX studio

### ISSUE THREAD

**Issue by Quenty** [Anaminus/roblox-bug-tracker#626]
https://medium.com/roblox-development/stopping-studio-crashes-af404540f4a0

Crazyman32's plugin uses the plugin saving API to save how much time has been spent in studio every second. This behavior itself is OK, but it turns out saving this often makes ROBLOX crash, probably due to a read/write conflict. For those who don’t know, ROBLOX saves plugin saved data to a JSON file. Combined with several copies of this plugin running (think: ROBLOX studio in play test mode), and you get a deadly combination of studio crashing.

Crazyman32 has updated his plugin, but you an still repro this by frequently saving/reading from a plugin save file while opening up multiple ROBLOX studio windows.

**Comment by zeux** [comment]
Is it possible to have some kind of a repro? E.g. a plugin that stresses load/save functionality to the point where it crashes frequently?

**Comment by Quenty** [comment]
Sorry, I can't provide a direct repro, but there's definitely some correlation, either with me disabling the plugin, or with ROBLOX fixing the whole glitch in an unrelated update.

It was never something that was directly reproducible, but a seeming random crash that would occur until I disabled the plugin. 

I'm sorry I can't provide a repro—I don't expect a whole lot to come from this bug report.
