### ISSUE TITLE
BillboardGui Mouse Detection Incorrect

### ISSUE THREAD

**Issue by OsyrisRBLX** [Anaminus/roblox-bug-tracker#629]
http://www.roblox.com/games/253573211/BillboardGui-Bug-Repro

I've displayed the bug in the place above. Mouse detection seems to be inverted vertically across the middle of the BillboardGui. Using TextButton.AutoButtonColor, you can see that the mouse is detected on the wrong GUI when you go to click on a button.

**Comment by matthewdean** [comment]
Fixed.
