### ISSUE TITLE
Changing SoundId to "rbxasset://" causes instant crash

### ISSUE THREAD

**Issue by JodeRBX** [Anaminus/roblox-bug-tracker#632]
Repro steps:

1. Create a new Sound instance, either by script or otherwise.
2. Set its SoundId to the string "rbxasset://", either by script or otherwise.
3. Select the Sound in Studio. Setting the selection via the Selection service also works, even if the properties and explorer windows are closed.
4. The Roblox Studio window will instantly close with no visible error; the process will stop shortly after.

Because it is necessary to select the sound, this cannot be used to crash the client; however, a plugin could crash studio in this manner.

**Comment by matthewdean** [comment]
Looks fixed.

**Comment by DarkMistyMittens** [comment]
I'm a iMac user and I use Roblox Studio all the time.I have this problem with changing the Sound ID as well.I think this only happens for iMac users, I'm not sure.Having 'SystemMenu' on Roblox Studio would probably crash when changing Sound ID or Particles Colour.Changing the layout to 'RibbonBar' it worked all perfectly well.I hope this helped. :)
I don't know if other people are facing this problem when changing the SoundID while using the 'SystemMenu' but I hope this really helps. ^^"
