### ISSUE TITLE
Games Page Bug

### ISSUE THREAD

**Issue by Monkeyman8446** [Anaminus/roblox-bug-tracker#635]
If you go to the new games page, then go to another page, then click the back arrow...
--->It brings back the old games page

**Comment by Anaminus** [comment]
I cannot reproduce this. Please read through the [contribution guidelines](https://github.com/Anaminus/roblox-bug-tracker/blob/master/CONTRIBUTING.md).

**Comment by Monkeyman8446** [comment]
Yea, sorry its probably chrome extensions

-----Original Message-----
