### ISSUE TITLE
Certain plugins cause "RenderStepped event can only be used from local scripts" error.

### ISSUE THREAD

**Issue by gergy008** [Anaminus/roblox-bug-tracker#636]
Certain plugins have been causing this error, which will activate whenever I attempt to use any of the smooth terrain tools.

    16:42:34.422 - RenderStepped event can only be used from local scripts
    16:42:34.422 - Script 'Plugin_-1.Terrain Tools.TerrainBrushScript', Line 339 - global quickWait
    16:42:34.423 - Script 'Plugin_-1.Terrain Tools.TerrainBrushScript', Line 763 - global Selected
    16:42:34.423 - Script 'Plugin_-1.Terrain Tools.TerrainBrushScript', Line 87
    16:42:34.423 - Stack End

The plugins I had activated at the time were the Animation plugin, Stravant's Minify&Beautify & Storage swap and finally I had another plugin that checks when players are online and alerts you through outbut. (Ro stalker, roblox stalker something like that)

When I removed all my plugins and restarted studio, the terrain tools worked fine. I have a feeling it's something to do with the animation plugin.

**Comment by Anaminus** [comment]
This is caused by a plugin inserting a NetworkServer object, which is a questionable practice. If it's a problem for you, you'll have to take it up with the author of the plugin.

**Comment by Gskartwii** [comment]
It is the Ro-Stalker plugin causing this. I contacted the author and he uploaded a fixed plugin.
