### ISSUE TITLE
'Clan' tab incorrectly displayed on other group tabs

### ISSUE THREAD

**Issue by Amiracle56** [Anaminus/roblox-bug-tracker#641]
On the groups page, the 'Clan' tab is incorrectly displayed on other group tabs.

At first, the 'Clan' tab completely covers the 'Games' tab. When switching to the 'Clan' tab, the 'Clan' tab is correctly displayed. After this, the problem is fixed and the 'Games' tab correctly displays the group's games. 

Here's a GIF of the issue: http://i.imgur.com/4S9Sebj.gif

To reproduce: 
1. Go to a group with a group game. I picked this group: http://www.roblox.com/My/Groups.aspx?gid=1173083. Make sure you join this group, too. 

2. Click the 'Clan' tab. 

3. Click the 'Games' tab. 

Logged out, the 'Clan' tab is the first tab that appears and the issue is fixed: http://i.imgur.com/hU0QxOQ.png

Also, if you navigate to other tabs the 'Clan' tab appears above the tab navigated to. Returning to the 'Clan' tab fixes the issue. 

Here's a GIF of that issue: http://i.imgur.com/FRce2zl.gif 

To reproduce:
1. Go to a group with a group game. I picked this group: http://www.roblox.com/My/Groups.aspx?gid=1173083. Make sure you join this group, too. 

2. Click on any other tab excluding the 'Clan' tab. 

3. Return to the 'Clan' tab to fix the issue.

Once again, logged out, the issue does not occur as the 'Clan' tab is first rather than the 'Games' tab: http://i.imgur.com/hU0QxOQ.png

The browser used in the GIFs and screenshots is Google Chrome. I have also tested this on Internet Explorer 11 and the result was the exact same as Chrome. My OS is Windows 8.1. 

This bug most likely occurred when group games were released, but I noticed it about a week ago. 

My ROBLOX username is Amiracie (http://goo.gl/Ns8SS1)

**Comment by MerelyRBLX** [comment]
The fix for this is going through the testing and will reach production soon.

**Comment by matthewdean** [comment]
@MerelyRBLX says it's fixed.
