### ISSUE TITLE
RenderStepped event can only be used from localscripts

### ISSUE THREAD

**Issue by RaysRevenge** [Anaminus/roblox-bug-tracker#643]
I am using the new smooth terrain tool but whenever I try to use a tool such as "add", I get this error:
"RenderStepped event can only be used from localscripts"

**Comment by Gskartwii** [comment]
Do you have a plugin that creates a NetworkServer?

**Comment by Anaminus** [comment]
This is a problem with one of your plugins inserting a NetworkServer object. This practice is no longer necessary, so you should contact the author of the plugin that is causing this issue.
