### ISSUE TITLE
i found 2 bugs

### ISSUE THREAD

**Issue by thekerbalwow** [Anaminus/roblox-bug-tracker#644]
1 is no walking sounds

2 what happen flat terrain

![capture](https://cloud.githubusercontent.com/assets/12002830/8153313/2c3788f4-12e9-11e5-9a65-73cc6d6feea6.PNG)

i clicked is shows loading screen text

**Comment by Anaminus** [comment]
Please preview the [guidelines](https://github.com/Anaminus/roblox-bug-tracker/blob/master/CONTRIBUTING.md) before contributing.
