### ISSUE TITLE
Negative LineHandleAdornment.ZIndex with AlwaysOnTop crashes

### ISSUE THREAD

**Issue by einsteinK** [Anaminus/roblox-bug-tracker#645]
A rendered LineHandleAdornment will crash studio under those circumstances:
- ZIndex is below -2
- AlwaysOnTop is set to true
- Adornee is set to a visible part

Not tested with other Adornments or with the camera far from the  adornment.

Works both in studio and online.

**Comment by Anaminus** [comment]
From [ROBLOX/Core-Scripts/issues/172](https://github.com/ROBLOX/Core-Scripts/issues/172#issuecomment-112096502):

I am able to reproduce this, but only if the ZIndex is less than -2.

**Comment by zeux** [comment]
Fixed.
