### ISSUE TITLE
Developer console not working in group-created games (via M39a9am3R)

### ISSUE THREAD

**Issue by ImageLabel** [Anaminus/roblox-bug-tracker#647]
"For games set up by a single owner, the owner can open the developer console and run code through the server tab of the console. However, when the owner sets up a group game, that is not the case. The owner of the game is able to load the developer console and read errors, but can not run code. The owner gets the result expected for non-owners."

Reproduction steps:
1. Create a game from the ["Group Creations"](http://www.roblox.com/develop/groups) tab
2. Join a server
3. Execute code from the server section of the developer console.

**Comment by einsteinK** [comment]
This is both a bug in the engine and a bug in the corescripts.
The corescript thinks anyone is the place owner.
The engine thinks only the user with the groupId as userId owns the place.
(There is a web API for this, but it doesn't get used properly, while it should)

**Comment by magiccube3** [comment]
Tested, problem fixed.
