### ISSUE TITLE
Neon Material disable when minimizing game.

### ISSUE THREAD

**Issue by ModerationHistory** [Anaminus/roblox-bug-tracker#649]
If there is neon material in game and you minimize that game then maximize the game again. It disables the neon material (Glow)

https://www.youtube.com/watch?v=9ccL3uuMJx4&feature=youtu.be

**Comment by SNCPlay42** [comment]
Doesn't neon only have its glow effect at a certain minimum quality level?

It's possible that when you minimise the game, ROBLOX lowers its quality level to reduce performance usage (no point rendering pretty stuff if you aren't looking at it) and that causes it to go below the quality level needed for the glow effect.

**Comment by bohdan77** [comment]
Well, I don't think ROBLOX should be rendering anything at all if it's minimized.

**Comment by Anaminus** [comment]
I'm unable to reproduce this (using [this place](http://www.roblox.com/games/257718952/ModerationHistorys-Place-Number-200)). Does the issue still occur for you? Can you post your computer specs (OS, CPU, GPU, etc)?
