### ISSUE TITLE
Kills and Wipeouts are no longer recorded on the website.

### ISSUE THREAD

**Issue by JasonTheOwner** [Anaminus/roblox-bug-tracker#651]
I've verified this for about two weeks, kills and deaths no longer are recorded from games from which Roblox profiles always reflected these gameplay stats in the past.

**Comment by matthewdean** [comment]
Not a bug.

**Comment by JasonTheOwner** [comment]
It should be a web bug at least

**Comment by matthewdean** [comment]
It's intentional behavior.
