### ISSUE TITLE
TextBoxes inside active, draggable GUI objects are dragged around when focus ends after clicking

### ISSUE THREAD

**Issue by GigsD4X** [Anaminus/roblox-bug-tracker#653]
Check it out yourself with the example file in https://github.com/Anaminus/roblox-bug-tracker/pull/654

**Comment by RobloxCodeWriter** [comment]
We're looking into this.

**Comment by NNickey** [comment]
Fixed? Just noticed I was able to click on textbooks..

**Comment by NNickey** [comment]
Box.

**Comment by ConorGriffin37** [comment]
This is fixed.
