### ISSUE TITLE
Hang Glider Bug

### ISSUE THREAD

**Issue by xxxxhlp** [Anaminus/roblox-bug-tracker#655]
When you are falling and you try to deploy a Hang Glider you will fling out and die.

**Comment by NNickey** [comment]
This is based on how the Hang Glider script works? Not related to roblox at all.

**Comment by Anaminus** [comment]
Please use the [asset bug tracker](https://github.com/matthewdean/roblox-asset-bug-tracker) for issues related to Gear.
