### ISSUE TITLE
Group creation name bug

### ISSUE THREAD

**Issue by UnionistsRBLX** [Anaminus/roblox-bug-tracker#656]
When I tried to create groups, some names do not work.

For example, I tried creating a group called [SG]     Republic of Singapore.

Note that the spaces between [SG] and Republic are 3 spaces.

It does not show up as it says that the name is taken. In fact, the name is not taken at all.

I also tried using Alt+255 as the space, the same dosen't work too.

In the past, multiple spaces in names work, but I have no idea why this does not work anymore.

I need to clarify whether this is a bug.

**Comment by Anaminus** [comment]
It is certainly intentional, so that names which look similar cannot be created.The following whitespace-related sanitation probably occurs:
- Leading and trailing whitespace characters are removed
- sequences of whitespace characters are collapsed into single normal space characters

**Comment by Sergeant2001** [comment]
So that's it? No solution to the problem? I'm  also having this problem and I tried using different browsers and it still didn't work.
