### ISSUE TITLE
Closing RobloxPlayer causes RobloxPlayer to crash.

### ISSUE THREAD

**Issue by magiccube3** [Anaminus/roblox-bug-tracker#660]
Crash details:
- - - - - - - - - - - - - - - - - - - - - - 
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	RobloxPlayerBeta.exe
  Application Version:	0.203.0.61342
  Application Timestamp:	559eba59
  Fault Module Name:	RobloxPlayerBeta.exe
  Fault Module Version:	0.203.0.61342
  Fault Module Timestamp:	559eba59
  Exception Code:	c0000005
  Exception Offset:	000a91be
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	c30d
  Additional Information 2:	c30d626c4d4152ddb4b20fbac3603045
  Additional Information 3:	ab60
  Additional Information 4:	ab60f13f5697465ccdf510a0885e6751
- - - - - - - - - - - - - - - - - - - - - - 
Windows 7

**Comment by Anaminus** [comment]
Needs reproduction steps.

**Comment by magiccube3** [comment]
There isn't too many repro steps.
I'm running Windows 7 Ultimate 32-Bit and when I play a game on Roblox, then close the game, RobloxPlayerBeta.exe crashes.

**Comment by TheSneak** [comment]
This happens to me, too.

Reproduction steps:
1) Start this game: http://www.roblox.com/games/113647/Imagination
2) Wait for the character to load
3) Exit the game by any of these methods:
    a) press alt-F4 
    b) click the close button on the game window
    c) use the hamburger menu to exit the game.
4) The standard windows crash dialog appears with options to 
    a) Check online for a solution and close the program
    b) Close the program
    c) Debug the program

System:
Windows 7 Ultimate SP 1 64 Bit
16 Gigs Ram
Core i5-2500
AMD Radeon HD 6800

**Comment by magiccube3** [comment]
I'm led to believe this may be a problem for Windows 7 Ultimate users.
None of my system specs cross with TheSneaks's.
