### ISSUE TITLE
Faulty Saving

### ISSUE THREAD

**Issue by bubbaman73** [Anaminus/roblox-bug-tracker#661]
So last night i added an update to one of my places and saved it, but when i tried to go make another update all that was in the workspace was a message that said the place was loading. A friend was able to play the game and it was all there.So i reverted back to an earlier version and it loaded again.

**Comment by magiccube3** [comment]
Not enough info.
Please read the contributing page before submitting a bug.
https://github.com/Anaminus/roblox-bug-tracker/blob/master/CONTRIBUTING.md
"If you don't understand what's going on, or you can't reproduce the bug, don't bother submitting an issue.
