### ISSUE TITLE
Developer Console Doesn't Show Anything

### ISSUE THREAD

**Issue by TheTalentedHero** [Anaminus/roblox-bug-tracker#663]
In my game, the developer console doesn't show anything. Its completely empty.
![robloxscreenshot07202015_214455143](https://cloud.githubusercontent.com/assets/8389751/8791748/f04940c0-2f2c-11e5-8a64-c70188d56fa6.png)

I don't have a real or correct way to recreate this issue, but I think if you rename a player's humanoid to something else other than the default name Humanoid, however, I don't think it recreates the issue.

**Comment by Anaminus** [comment]
Please use the [Core-Scripts](https://github.com/ROBLOX/Core-Scripts) issue tracker for issues related to the dev console.

**Comment by TheTalentedHero** [comment]
Oh, I didn't know that.
