### ISSUE TITLE
'Publish to ROBLOX As' Uneven display from use of icons

### ISSUE THREAD

**Issue by DeveloperBlue** [Anaminus/roblox-bug-tracker#671]
When Roblox switched from Thumbnails to Icons, one of the things it offset was the display panel when you click 'Publish to ROBLOX As'. 

File -> Publish to ROBLOX As

See here as the first row is uneven due to the "New Place" button is in thumbnail from.

![ss 2015-07-22 at 04 56 14](https://cloud.githubusercontent.com/assets/11480933/8837094/ab60cdc2-3092-11e5-808a-043f08ca53c8.jpg)

**Comment by matthewdean** [comment]
Fixed.
