### ISSUE TITLE
Mobile portrait mode, jump button obstructs move.

### ISSUE THREAD

**Issue by NNickey** [Anaminus/roblox-bug-tracker#675]
![screenshot_2015-07-27-06-50-04](https://cloud.githubusercontent.com/assets/3466265/8906600/31872700-342d-11e5-8c48-12b9e27350af.png)

**Comment by Anaminus** [comment]
According to [this issue](https://github.com/ROBLOX/Core-Scripts/issues/193) in Core-Scripts, portrait mode isn't supported.
