### ISSUE TITLE
Mobile landscape mode, NPC prompt chat can get obstructed by top GUI.

### ISSUE THREAD

**Issue by NNickey** [Anaminus/roblox-bug-tracker#677]
![screenshot_2015-07-27-07-22-58](https://cloud.githubusercontent.com/assets/3466265/8907039/9af32f9c-3430-11e5-82b8-a0be30e2da85.png)
![screenshot_2015-07-27-07-21-24](https://cloud.githubusercontent.com/assets/3466265/8907042/a149020e-3430-11e5-9419-d5d400ca2968.png)

**Comment by magiccube3** [comment]
The ZIndex of the NPC chat must be of less priority than the CoreGui.
This is not a bug.

**Comment by Anaminus** [comment]
It is a bug; the GUI should be positioned to accommodate the edge of the screen, as well as the topbar.

However, Dialogs are controlled by core scripts, so this bug should be submitted to the [Core-Scripts](https://github.com/ROBLOX/Core-Scripts) issue tracker.
