### ISSUE TITLE
Mobile screen resolution changed issue.

### ISSUE THREAD

**Issue by NNickey** [Anaminus/roblox-bug-tracker#678]
When changing from landscape to portrait mode, roblox does not change the resolution and stretches. Same occurs when changing from portrait to landscape. But never stretches when you first join the game in your preferred orientation.
![screenshot_2015-07-27-07-23-29](https://cloud.githubusercontent.com/assets/3466265/8907090/fc076be0-3430-11e5-82f0-f96206aa540b.png)
![screenshot_2015-07-27-07-23-22](https://cloud.githubusercontent.com/assets/3466265/8907087/f3fdf392-3430-11e5-9185-9314489ca760.png)

**Comment by Anaminus** [comment]
According to [this issue](https://github.com/ROBLOX/Core-Scripts/issues/193) in Core-Scripts, portrait mode isn't supported.

**Comment by magiccube3** [comment]
If portrait mode isn't supported, why does it exist?
Shouldn't it be just so users can only view the Roblox game in one of the two landscape modes?

**Comment by SNCPlay42** [comment]
That is indeed the case. As the issue Anaminus linked to shows, the submitter can get around the restriction to landscape because their phone is rooted.

**Comment by NNickey** [comment]
If you seen my other issues, portrait mode will work just fine, just the start button needs to move over and it'll work
