### ISSUE TITLE
Website issue - Visits to Own Places incrementing when visited by Self

### ISSUE THREAD

**Issue by JasonTheOwner** [Anaminus/roblox-bug-tracker#682]
In the past, if you visited your own place, those visits would not count.  But the current behavior is counting these visits, and is unexpected behavior based on previous experience.  

During a testing phase, I would rather not see a number of visits being registered to a place, and in the past I've disabled a place if I felt people other than myself were visiting.  Now its hard to tell if the visits are from others or only my own, because it counts my visits and others.

I have not tested if the reward tix are being issued by visits to my own place yet - will verify if this happens as well, later.

**Comment by Squidcod** [comment]
logged internally

**Comment by magiccube3** [comment]
Reward tix are not issued when you visit your own place.
Increased visit count by visiting your own place is intentional. (Not a bug)
I do think this was a bad move, in my opinion.
