### ISSUE TITLE
Neon material glow applied to non-neon CSG part [engine] [bug]

### ISSUE THREAD

**Issue by Feralidragon** [Anaminus/roblox-bug-tracker#688]
How to reproduce:
- Add a part, set its material to "Neon"
- Add 2 more parts, set one of them to negate and apply an union on them (generating a new CSG part in the process)
- Add a decal to one of the sides of the new CSG part created in the previous step

Whenever both the Neon and the CSG+decal parts are in view, the CSG one will also glow the same way the Neon part does.
Whenever only the CSG part is in view, it will render normally as it should.
It seems only an union + decal causes this bug, since a normal part with decal or a CSG part without a decal do not have this bug.

Here are some screeshots of the problem:
![neon_bug1](https://cloud.githubusercontent.com/assets/6334764/9155713/b0bb24b4-3eb8-11e5-81b1-add44e07ab52.jpg)
![neon_bug2](https://cloud.githubusercontent.com/assets/6334764/9155714/b0bd75f2-3eb8-11e5-90ad-d7fdfdf9ceeb.jpg)

And also the rbxl file these screenshots were taken from:
http://www.mediafire.com/download/da3yrx39s0nzccx/neon_bug.rbxl

**Comment by Feralidragon** [comment]
Any news on this?

We're in 2016 already and this bug doesn't seem to have been fixed yet, and it seems a rather critical rendering bug to me since this means we can't use neon materials at all under normal conditions (we can't use CSG with decals otherwise the bug always happens), and from what I checked more people reproduced this exact bug under the same exact way.

This bug has been pretty much the only reason why I stayed away from trying to develop for Roblox in the first place, since while it remains unfixed I can't really create what I want to create...

If more info is needed from my end please let me know.

**Comment by Gskartwii** [comment]
[Apparently it just got fixed](http://devforum.roblox.com/t/rendering-fixes/21261)

**Comment by Feralidragon** [comment]
Oh, cool, thanks for the heads up :+1: 
I just opened the studio again and I can confirm it's fixed. :D
