### ISSUE TITLE
Billboardgui - Would like it to scale in the opposite direction [Enhancement]

### ISSUE THREAD

**Issue by JasonTheOwner** [Anaminus/roblox-bug-tracker#702]
I'm trying to make use of the Billboardgui - no matter whether I set ONLY the scale or ONLY the offset on the GUI, or its children, I still get the same undesirable behavior when using an ImageLabel inside a Frame - it shrinks as I get close, and it grows as I walk away.  If it would do just the opposite, it would be what I want - I want it to look smaller, in relation to the distance away I am, and get bigger as I get closer (but reasonably big).  I just want to do a simple thought cloud containing an image like you see in so many other games (like the Sims).  Can a Boolean value be setup to allow it to scale the opposite direction from what its been doing, if there's no current solution with the current code set? (I haven't found one yet)

**Comment by Anaminus** [comment]
The GUIs are actually staying the same size. If you want them to resize with distance, then set the Scale component of the BillboardGUI's Size. This will scale the BillboardGUI such that a value of 1 will be the length of 1 stud.
