### ISSUE TITLE
Whom can I report this to?

### ISSUE THREAD

**Issue by magiccube3** [Anaminus/roblox-bug-tracker#703]
There's a vulnerability in roblox's 'process' (per say) which lets people do disturbing things on roblox.
(Further details are not provided in order to prevent further abuse)
Posting here would inevitably lead to a spike in unwanted content shown to roblox players.
Who is a a valid person to report this to who can forward it to the correct team to handle this?
(No, this is not the obvious R-Rated unfixable script issue)

**Comment by matthewdean** [comment]
You can [send a private message](http://www.roblox.com/messages/compose?recipientId=66766775) to ConvexHero. He is the admin responsible for dealing with security issues.
