### ISSUE TITLE
Screeching Sounds When Opening ROBLOX Studio Place

### ISSUE THREAD

**Issue by MrJimenex** [Anaminus/roblox-bug-tracker#705]
I have detected a screeching/distorted sound when opening any ROBLOX Studio Place, and I believe this is occurring only with Windows 10 Operated Computers

Many have talked about this and usually this happens because whenever a new Operating System is released, it takes some days for companies to go and make it compatible, or optimize, as I would say, for any new Operating Systems, as in this case, Windows 10, and likely OS X El Capitan

Yes, this is also occurring with ROBLOX Player as well, as the program opens and starts loading the place.

**Comment by Jody7** [comment]
https://github.com/Anaminus/roblox-bug-tracker/issues/701
