### ISSUE TITLE
TeleportService VIP Server Bug

### ISSUE THREAD

**Issue by Slappy826** [Anaminus/roblox-bug-tracker#710]
While I at was at [Voidacity's Script Builder](http://www.roblox.com/games/20279777/Voidacitys-Script-Builder-Working-Local)  I found this strange bug when using 
```lua
TeleportService:TeleportToPlaceInstance()
```

if you goto a VIP server and run
```lua
game:GetService("TeleportService"):TeleportToPlaceInstance(game.PlaceId, game.JobId, Player)
```
it will say "Teleport Failed" but at the same time, the server disconnects you. It will eventually say you lost connection even though you didn't.

*Notice: Voidacity has a sandbox that blocks TeleportService, you will have to try it at a different place. (I have a sandbox bypass.)*

**Comment by Anaminus** [comment]
Please read the [guidelines](https://github.com/Anaminus/roblox-bug-tracker/blob/master/CONTRIBUTING.md#things) before contributing. This is going to need reproduction steps that do not involve a Script Builder.
