### ISSUE TITLE
Deprecated properties of BodyAngularVelocity not hidden

### ISSUE THREAD

**Issue by badcc** [Anaminus/roblox-bug-tracker#712]
![BodyAngularVelocity Property View](http://i.imgur.com/9voxzSA.png)

**Comment by matthewdean** [comment]
What makes you think those properties are deprecated?

```
Class BodyAngularVelocity : BodyMover
	Property Vector3 BodyAngularVelocity.AngularVelocity
	Property Vector3 BodyAngularVelocity.MaxTorque
	Property float BodyAngularVelocity.P
	Property Vector3 BodyAngularVelocity.angularvelocity
	Property Vector3 BodyAngularVelocity.maxTorque
```

**Comment by badcc** [comment]
@matthewdean  All of the other body objects had camelCase properties deprecated for CamelCase alternatives on August 27, 2015.

**Comment by DarraghGriffin** [comment]
Will fix this. It was intentional to not deprecate the properties until 210 was on iOS and Android because it caused issues with replication of the properties to legacy clients.

**Comment by matthewdean** [comment]
Fixed.
