### ISSUE TITLE
Remove enhancement tag

### ISSUE THREAD

**Issue by Anaminus** [Anaminus/roblox-bug-tracker#715]
It has been suggested that enhancements do not fit the format of this tracker, which is primarily related to bugs. I can agree, but I'm open for comments for/against the disallowing of feature requests.

## Enhancements vs Bugs

An issue can be considered an enhancement if:
- it adds a new feature.
- it adds a new part to an existing feature.
- it changes a part of an existing feature.

However, an enhancement can be considered a bug if:
- it addresses an existing part of a feature that is problematic.
- it addresses a missing part of a feature that makes the feature problematic, or causes the the feature to be "incomplete".

## Reclassification

The following open issues have the `enhancement` tag. If you think there are issues that can be reclassified as bugs, then make a comment stating how they should be changed/reworded.

- ~~#33: Make build tools not modify the Transparency property when collision check is disabled~~
- #34: Detect indentation when wrapping text in script editor
- #47: Move cookies out of registry to temporary folder
- ~~#76: The object browser has no icon for protected callbacks~~
- #78: Add API generator to Studio
- #94: Studio Does not Associate Place with File
- #170: The ability to selectively ray cast parts
- #194: It should be possible to rearrange game passes on game pages
- ~~#197: Instance.archivable, BodyPosition:lastForce, BodyVelocity:lastForce and FormFactorPart.formFactor are not deprecated~~
- #202: Scripts in Workspace run before scripts in ServerScriptService
- #204: ZIndex is limited to 10 layers only and does not scale well. 
- #213: Tables passed as input to the API do permit mixtures of string keys and arrays
- #217: Humanoid.TargetPoint is filtered by workspace.FilteringEnabled
- #222: Certain UserInputTypes only correspond with one UserInputState regardless of actual UserInputState
- #246: There should be an AssetType enumeration
- #261: DataStoreService does not allow removal of data
- #262: Add ImageRectOffset and ImageRectSize properties to Tools and HopperBins
- #274: Use full name when two or more script tabs are opened
- #275: Add Enabled property for ScreenGuis
- #276: Add shortcut for Clear Output action
- #281: MarketplaceService.PromptPurchaseFinished should report price and currency
- #287: Move ExportPlace and ExportSelection to Plugin
- #288: Create a Badge Spotlight section
- #308: Implement manual code folding regions
- #311: Do not truncate script name in error message
- #326: Add debugger panel that lists variables in current stack frame
- #345: Machine-readable API dump
- #378: New UserInputService.TextBoxFocusReleased event has no enterPressed parameter
- #389: Physics should simulate around the Camera/CameraSubject instead of the character
- #405: Add LocalScripts and ModuleScripts as file types in file insert dialog
- ~~#445: PlayerAdded event does not fire for LocalScripts~~
- #564: Studio command-line mode
- #567: Better custom chat GUI support
- #572: Allow custom font sizes in GUIs.
- #576: Scriptable pricing for dev products
- #593: Vector3.new() Bug
- #606: Feature Request: Callback for sound.TimePosition changes
- #674: TweenRotation
- #686: Player Funds Are Publicly Visible [Website] [Enchancement]
- #694: Nvidia Optimus - Set dedicated graphics card by default [enhancement]
- #704: UDim2Value and Vector2Value Objects
- #708: Publishing a place to Roblox does not notify you if it is an open-source slot.

**Comment by TheSneak** [comment]
I am for allowing feature requests here.  I see nothing about the format of this tracker that would preclude the inclusion of enhancements. I'm unaware of any legitimate issue tracker that excludes enhancements and focuses solely on bugs. 

There are precious few resources available to ROBLOX users to communicate effectively with the developers. Let's not hobble this one.

**Comment by chc4** [comment]
I'm in favor of allowing small-scale feature requests and enhancements to current features, or for new features that are small in scope. It makes sense that they would be logged here for posterity and to gauge feedback on the requests. A feature request of "add xyz to the script editor pane" is in some sense a bug, where it's missing a key feature that should be implemented to complete the editor.

Outrageous requests or items of questionable use, though, don't really belong here, but I haven't seen that many issues like that being opened.

**Comment by DeveloperBlue** [comment]
#708 can be considered a 'bug' in terms of 'it addresses a missing part of a feature that makes the feature problematic, or causes the the feature to be "incomplete".

Can you imagine publishing your complete game or alpha out onto a place slot you left un-copy locked a year ago? Owch.

**Comment by Feralidragon** [comment]
#694 is pretty much a bug, considering that by not selecting the dedicated card by default many of the modern features simply do not work at all (neon material does not glow, smooth terrain water reflective and refractive effect doesn't work, etc).

**Comment by CoffeeFlux** [comment]
Most of the enhancements I see on here strike me as reasonable, and this is really the best forum for that kind of thing. I see no reason to unnecessarily cripple our ability to suggest small changes.

**Comment by DeveloperBlue** [comment]
Have we come to a consensus on posting about enhancements?

**Comment by Anaminus** [comment]
I'm going to keep enhancements.
