### ISSUE TITLE
ChatMakeSystemMessage glitch affects coregui chats

### ISSUE THREAD

**Issue by DiamondBladee** [Anaminus/roblox-bug-tracker#716]
I love that Roblox is allowing us to play with the CoreGui more, but this bug needs to be fixed before anyone is going to use the system message feature.

`game:GetService("StarterGui"):SetCore("ChatMakeSystemMessage",{
	Text = "Hello!",
	Color = BrickColor.new("Pink").Color
})`

Expected:

The system message will be pink and all other chats will remain white.

Bug:

All other chats from then on are pink, not the default white.

**Comment by SNCPlay42** [comment]
Core script bugs should be submitted to [ROBLOX/Core-Scripts](https://github.com/ROBLOX/Core-Scripts), the official repository for CoreScripts.

(Looks like there's a [commit to fix this](https://github.com/ROBLOX/Core-Scripts/commit/91dd98948b693a7b18513fde18b0dbbb3cd723a8) already.)
