### ISSUE TITLE
Changing pages within the Studio Browser causes the user to log out.

### ISSUE THREAD

**Issue by AdarkTheCoder** [Anaminus/roblox-bug-tracker#718]
This is on Windows 10, and I have a feeling it's related to the 'Script signature verification failed...' error.

Repro: log in to Studio's default splash page, go to 'My Project', then 'Group Creations', and change to a different group:

http://puu.sh/k7vxD/469262c5af.png --Logged in, showing the Group Place I have access to.

http://puu.sh/k7vyl/3e3fb79fba.png --Changing to a different group logs me out.

Changing to 'Classic View' and clicking through to almost any other page on the ROBLOX website within Studio also forces a logout.

(Also of note is that ROBLOX Studio never stays logged in after you close in on Win10)

**Comment by Squidcod** [comment]
I wasnt able to reproduce this issue.  Is anyone else having this issue? How are you logging in when you first log in?  From the website or from in studio? Any weird network things that could be causing an issue?  School network, aggressive antivirus or firewall and so on...

**Comment by AdarkTheCoder** [comment]
I'm on a university network, but it has no restrictions that I am aware of: no blocked sites or throttling or anything like that.

I'm logged in through Firefox, and it has no problems staying logged in. The computer that has Win10 doesn't actually have an antivirus installed and Windows Firewall is configured to ignore ROBLOX.

Every time I open Studio it goes to the default splash page, then I click 'My Projects' and log in from there: http://puu.sh/k7HN5/d99fc28ea5.png

After it switches me back to the New Project page, I can go back to My Projects and see all my saved places, and then I go to Group Creations and those two screenshots show what happens after that.

**Comment by Squidcod** [comment]
Are you logging in with username/Pass or facebook?
Are you on WiFi?
Does your university change IP during active use?

I still cant reproduce the issue yet, but this is definitely helping I will add it to the defect when I enter it in our DB.

**Comment by AdarkTheCoder** [comment]
Username/Pass, Wired, and constant static IP.

**Comment by AdarkTheCoder** [comment]
I found another way to reproduce this using plugins, so I made a video, but then suddenly opening a Place from Firefox worked. And then it didn't.

https://youtu.be/eIesP1MTHMg

**Comment by Squidcod** [comment]
I've entered what we've got in our internal db.
I dont know when it may be addressed.

**Comment by AdarkTheCoder** [comment]
Thank you. I've got a workaround now, so it's not as urgent, but it is a very strange bug.

**Comment by ThrownException** [comment]
I have the same issue, but for me it is when publishing places.
I have Windows 7 Ultimate (x64)

I log in, open my local file, click on "Publish to ROBLOX as..." and it says "You need to login to perform those actions!" and logs me out.

I contacted info@roblox.com and they are forwarding this issue to the ROBLOX engineers.

I have tried:
Allowing RobloxPlayerBeta and RobloxStudioBeta in the firewall
Uninstalling, rebooting and re-installing
Clearing the cache (using CCleaner, which cleared all my browsers cache)
Resetting IE settings and rebooting (which made it worse)
and re-installing (without uninstalling) and rebooting

I also tried to see if it was Malwarebytes or my AV causing the issue, disabled both and nothing happened.

**Comment by Anaminus** [comment]
Is this still an issue?

**Comment by AdarkTheCoder** [comment]
It was two days ago, don't have the Win10 computer until next monday to test again.

**Comment by ThrownException** [comment]
It's a bug in Studio.

What fixed it for me was to login on the site, go to the place you want to
edit and click "edit" and you should be logged in permanently. You can even
switch accounts if you want to.

**Comment by AdarkTheCoder** [comment]
Yes, that was my workaround - the problem with that is you can't load account-based plugins (only the old style of manually downloading and placing them in the plugins folder works, and you can't load *your* models, only Free Models.

**Comment by ThrownException** [comment]
Plugin loading works for me.

They probably don't support Windows 10 fully yet or something.

**Comment by AdarkTheCoder** [comment]
I meant to say intall - that requires being logged in. Installed plugins work fine.

**Comment by ThrownException** [comment]
Installing plugins also works for me. Try disabling your AV or antimalware
to see if it is something blocking something.

**Comment by AdarkTheCoder** [comment]
@Anaminus Yes this is still an issue. Just tested with the most recent Studio update on my lab computer that has this issue. This video: https://www.youtube.com/watch?v=eIesP1MTHMg&feature=youtu.be is still accurate.

@ThrownException The computer in question (my lab computer) does not have antivirus installed other than windows defaults, which ROBLOX is configured to be ignored in. The antimalware does not have active protection enabled.

This: http://puu.sh/lffbr/c0206d38f0.png appears when clicking the 'Manage Plugins' button on the Plugins toolbar in Ribbon mode.

**Comment by AdarkTheCoder** [comment]
After a Windows update, this appears to be working again. Not sure if ROBLOX also updated anything, but I'm no longer having this issue at all.
