### ISSUE TITLE
Launching games from Google Chrome is broken

### ISSUE THREAD

**Issue by samfun123** [Anaminus/roblox-bug-tracker#719]
Whenever I launch a game from Google Chrome the game never launches. It does it's little loading screen and then recommends me to download ROBLOX again. I believe the problem is because I see a document in networking tab of the developer tools that gets canceled:
`roblox-player:1+launchmode:play+gameinfo:+launchtime:+placelauncherurl:+browsertrackerid:`
(I have removed most the data)

I have been able to launch on Internet Explorer but that seems to be using an older version of the launcher.

My Computer has:
Google Chrome is running version 45.0.2454.85 m (With no extensions enabled)
Internet Explorer is running version 11.0.9600.17905
Windows 8.1

**Comment by Slappy826** [comment]
Was not able to reproduce.

**Comment by UnionistsRBLX** [comment]
I have a similar problem which it always shows the "Download Roblox" when I
have it downloaded already :/

On Sun, Sep 13, 2015 at 2:05 AM, Slappy826 <notifications@github.com> wrote:

> Was not able to reproduce.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaminus/roblox-bug-tracker/issues/719#issuecomment-139804025>
> .
>



-- 
Confidential Information.

**Comment by samfun123** [comment]
After re-installing roblox and restarting chrome I was able to play for a bit but then I couldn't play anymore.

**Comment by PhoenixVortex** [comment]
It's maybe because of the launcher extension. Sometimes Roblox doesn't
update their launchers frequently. Although this is a (maybe) cause. Don't
think that it is because of my post, it's just my opinion.

On Mon, Sep 14, 2015 at 2:02 AM, samfun123 <notifications@github.com> wrote:

> After re-installing roblox and restarting chrome I was able to play for a
> bit but then I couldn't play anymore.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaminus/roblox-bug-tracker/issues/719#issuecomment-139879226>
> .
>



-- 
Thanks,

Flamer_MW3

**Comment by samfun123** [comment]
This looks like it's fixed.
