### ISSUE TITLE
AdService.VideoAdClosed event always returns false for adShown

### ISSUE THREAD

**Issue by MerelyRBLX** [Anaminus/roblox-bug-tracker#722]
The VideoAdClosed event has an adShown parameter. However, this parameter always returns false, even when the ad has been displayed.

Repro: Create a LocalScript in StarterGui with the following code. Join the game on a phone or tablet on a non-Builders Club account. The ad will display but adShown will be false.
```
game:GetService("AdService").VideoAdClosed:connect(function(adShown)
   print("adShown: " .. adShown)
end)
wait(5)
game:GetService("AdService"):ShowVideoAd()
```

**Comment by Anaminus** [comment]
Is this still an issue?

**Comment by matthewdean** [comment]
AdService no longer works so this bug does not apply
