### ISSUE TITLE
Removing HumanoidControllers no longer prevents players from moving

### ISSUE THREAD

**Issue by samfun123** [Anaminus/roblox-bug-tracker#724]
In ROBLOX if you wanted to make it so a player couldn't move or jump you could simply remove their HumanoidController and then give it back to them to enable their controls. (See [the wiki](http://wiki.roblox.com/index.php/Controlling_a_Player's_Character))
But it looks like that functionality has been removed and removing the HumanoidController no longer stops the player from moving or jumping.

So it would be nice if developers had either control of the players movements by the way of some properties or just making it so removing their HumanoidController would disable a player's movement.

**Comment by AdarkTheCoder** [comment]
The new JumpPower property added to Humanoids allows devs to disable jumping (or amplify it), along with setting WalkSpeed to 0.

To stop the rotation of the character (for instance in first person moving the camera around) - setting AutoRotate to false (also a property of Humanoid) works while still allowing physics to be applied to the Characters.

Setting all three; JumpPower = 0, WalkSpeed = 0, AutoRotate = false; effectively disables player motion without having to anchor any Parts.

**Comment by Anaminus** [comment]
Humanoids are now entirely controlled by scripts, located in `Player.PlayersScripts.ControlScript`. This can be changed globally by putting the scripts under `StarterPlayer.StarterPlayerScripts`.
