### ISSUE TITLE
Lua strings are not handled correctly

### ISSUE THREAD

**Issue by cntkillme** [Anaminus/roblox-bug-tracker#730]
Strings with NUL characters in them terminate after that point, which would make sense normally but Lua strings allow embedded zeros, as such the length of the string is determined by the compiler. However when Lua strings are used by Roblox, it is cut off at the first NUL character. Generally, this would not be a problem unless one is storing binary data in StringValues, DataStore, etc. However in specific situations, this causes problems.

**Reproduction:**
`local val = Instance.new("StringValue");`
`local str = "hello\0there";`
`val.Text = str;`
`print(#str, #val.Text); ---> 11, 5 as opposed to 11, 11`

I'm not sure whether this was overlooked but it has been a problem for years and my solution (use 255-sized bytes by ones' complementing all bytes when saving, as such all values from 0 to 254 can be saved) is not ideal for many situations. One less bit per byte to work with in bitfields, serious loss of usable values with multi-byte values (2+ byte integers and pointers, floats and doubles, etc.). I can do what I need to do fine in Lua, but I planned on saving data that will more than not contain NUL characters in a StringValue or a DataStore.

**Update (Nov. 15, 2015):**
Also, the same thing happens when trying to send strings with NUL characters to the server/client from the client/server using *RemoteEvents* (I'm sure the same applies with everything else). Can I assume *EVERYTHING* done on Roblox's end treats Lua strings are regular C strings?
I get that it might be for safety precautions, but a whitelist would be great (like for StringValues/DataStores/etc.).

**Comment by Bosswalrus** [comment]
Yeah

**Comment by TickerOfTime** [comment]
True tho

**Comment by Anaminus** [comment]
This problem is so deeply rooted that it's basically impossible to change. The cost is not worth the gain, to the point that I'm going to assume that it will never be fixed.

However, there is the BinaryString type. This handles Lua strings properly, but it currently exists only for data serialization. Perhaps getting this type exposed to the Lua API would be a viable alternative.
