### ISSUE TITLE
Animations not being uploaded to Roblox correctly

### ISSUE THREAD

**Issue by Juddily** [Anaminus/roblox-bug-tracker#731]
In Roblox's animation editor, the animation appears normal. This particular animation has two frames, one at the beginning, and one at the end. The animation is .5 seconds long.

![Animation Editor](http://puu.sh/lfPBL/f9f944ee92.jpg)

However, when played back in studio, the orientation of the animation is not correct.

![Broken Animation](http://puu.sh/lfPRu/6a129156a5.jpg)
![Broken Animation](http://puu.sh/lfPWl/02cdba00d2.jpg)

I am uncertain if this problem is only occurring for me, or only certain people, because the first I have noticed this issue is sometime in July, and it has yet to be fixed. Additionally, I can provide no further explanation on how to reproduce this glitch. All I'm doing is exporting the animation normally, and it isn't working.

**Comment by Anaminus** [comment]
This needs more information. Particularly whether or not this is caused by the animation editor. If that turns out to be the case, then this issue should be submitted to the [Studio-Tools](https://github.com/ROBLOX/Studio-Tools) repository. The issue may also have been fixed since.
