### ISSUE TITLE
Plugin ModuleScripts can't access the global "plugin"

### ISSUE THREAD

**Issue by Gskartwii** [Anaminus/roblox-bug-tracker#736]
When you have a plugin that contains a regular script that requires a ModuleScript, the regular script will have access to the global variable `plugin`, but any ModuleScripts it requires (even if they are a part of the plugin) don't.

**Comment by Anaminus** [comment]
Modules don't inherit the environment of calling scripts, because they can be required from multiple sources. If you need a module to have access to the plugin, you'll have to pass the variable to the module. For example...

```lua
-- Module
return function(p)
	print("Plugin:", p)
end

-- Script
Func = require(script.Module)
Func(plugin)
```
