### ISSUE TITLE
BindableEvents don't play nice with custom userdata

### ISSUE THREAD

**Issue by eLunate** [Anaminus/roblox-bug-tracker#739]
Firing a BindableEvent with a `newproxy()` userdata results in connected functions being passed nil in its place. This should not be happening at all, and there is no reason that the bug should exist in the first place. 

**To reproduce:**
```
local n = Instance.new('BindableEvent');
n.Event:connect(print);
n:Fire(newproxy(true),newproxy(false));
```
Outputs `nil nil`

**Comment by Anaminus** [comment]
Duplicate of #740.
