### ISSUE TITLE
When awarding a badge, the pop-up message shows the wrong creator.

### ISSUE THREAD

**Issue by LucasWolschick** [Anaminus/roblox-bug-tracker#744]
I have a group game which awards a group badge. When awarding the badge, the "You won XXXX badge" GUI appears, but instead of showing the group name as it's creator, it shows the username with the same ID as the group.

To reproduce it, just try awarding a badge in a group and pay close attention at the "You won XXXX badge" GUI.

**Comment by Gskartwii** [comment]
You probably want to submit this issue to [the Core-Scripts repository](https://github.com/roblox/core-scripts) instead.

**Comment by matthewdean** [comment]
Fixed.
