### ISSUE TITLE
Clicking on Max speed property on Vehicleseat Causes Studio to crash

### ISSUE THREAD

**Issue by Duskitty** [Anaminus/roblox-bug-tracker#750]
Was trying to make a car/edit an existing one, and clicking on the Max Speed Property Caused my game to Crash, i dont know if this is a known bug or not, but it happens every time i try to do it

I know more or less for a fact it used to work

Im using windows 8.1 if that's needed

![aa2c09394fe40559e3e2430e8d3c129b](https://cloud.githubusercontent.com/assets/13949321/12361752/9381edca-bb85-11e5-96e2-1183495a9039.gif)

**Comment by The0neThe0nly** [comment]
Seems to be working fine for me. Could you include your place and/or any specific properties you are using?

**Comment by Duskitty** [comment]
Oh, Nevermind, it's working now, i just needed to Update studio ^^' sorry about the inconvinence, it used to crash studio reguardless of the place
