### ISSUE TITLE
Trying to change some GUI properties crashes Studio

### ISSUE THREAD

**Issue by Gskartwii** [Anaminus/roblox-bug-tracker#751]
Reproduction:

1. Create a GuiObject, such as TextLabel
2. Go to its properties
3. Try to change one of the following properties: Rotation, TextStrokeTransparency, TextTransparency
4. Roblox Studio crashes

I'm not sure, but it is possible that this is related to the new update with sliders for changing some properties.

**Comment by The0neThe0nly** [comment]
I am unable to reproduce this issue. Do you have a specific place that this works on?

**Comment by Gskartwii** [comment]
The issue seems to have disappeared after I upgraded.
