### ISSUE TITLE
http://www.roblox.com/User.aspx?UserName=%s redirects to the wrong location

### ISSUE THREAD

**Issue by mark-otaris** [Anaminus/roblox-bug-tracker#752]
The URL `http://www.roblox.com/User.aspx?UserName=%s`, where %s is a username, redirects to a login page if not logged in and to the current user's profile page otherwise. In the past, it redirected to the profile page of the user with username %s. This breaks *a lot* of links. I also don't know if there is a new URL that can be used to redirect to a user's profile from the user's username.

**Comment by BinaryResolved** [comment]
This is still a issue.

**Comment by mark-otaris** [comment]
It was fixed!
