### ISSUE TITLE
TerrainBrushScript Error

### ISSUE THREAD

**Issue by gamenew09** [Anaminus/roblox-bug-tracker#756]
The script `TerrainBrushScript` errors when you have a model, or some object, that is the same name as `Terrain`.
The script will need updating to look for the `Terrain` object type instead of looking for the name of `Terrain`.

Error:
```
20:17:26.890 - IsSmooth is not a valid member of Model
20:17:26.891 - Script 'Plugin_-1.Terrain Tools.TerrainBrushScript', Line 4
20:17:26.891 - Stack End
```

Let me know if you need reproduction steps.

**Comment by correlating** [comment]
I am unable to replicate this, I created a Model directly under Workspace named "Terrain".
Reproduction steps?

**Comment by gamenew09** [comment]
1. Create the model like you did with the name of Terrain.
2. Save and reopen the place.

You should then get the error.

**Comment by correlating** [comment]
Unable to reproduce it even with the reproduction steps above, I believe you are the only one experiencing this issue, send me your place file.

**Comment by gamenew09** [comment]
It seems to have been fixed, I can't reproduce it myself either.
