### ISSUE TITLE
Editing Complex Unions in Any Other Place Than the One They Were Created in Causes Studio to Stop Responding [No Crash/Unsolvable Message]

### ISSUE THREAD

**Issue by JayManLive** [Anaminus/roblox-bug-tracker#760]
Editing a complex (mostly round in my experience) union in another place where it wasn't originally created (Empty Baseplate for example) causes Studio to stop responding. This applies to any operation, Union, Negate and Separate. If you were to keep your original Studio window opened, and copy/paste your complex union in another place opened in a different window, when attempting to edit the union, the new window will become unresponsive, while the original window will successfully carry through with its task.

There was one situation I encountered where publishing a place, then re-opening it later caused Studio to become unresponsive when attempting to editing a complex union.

After this happens, the complex union cannot be recovered. In my experience, I had to restart one union 7 times, and still ended up with the same result, despite using different methods to creating the union.

**Comment by The0neThe0nly** [comment]
If you have a reproduction example place file or specific steps, posting them would be much appreciated.

**Comment by JayManLive** [comment]
Turns out that this was fixed in a recent update.
