### ISSUE TITLE
Cannot load assets using RBXCDN URLs

### ISSUE THREAD

**Issue by Gskartwii** [Anaminus/roblox-bug-tracker#761]
Sometimes, only *.rbxcdn.com URLs for assets hosted on Roblox, such as avatar headshots, are available. When used as the Image of an ImageLabel/Button, a message like so can be seen in the output:
```
Image failed to load StarterGui.ScreenGui.ImageLabel.Image : http://t2.rbxcdn.com/86737c5002424ffdfd16f91b1869ae90 because Request failed
```
`game:GetObjects` displays such an error when loading models:
```
Unable to load http://c2.rbxcdn.com/c6fe6dd7ef02269738c1321372e72db0
```

However, setting the Image to a roblox.com URL that *redirects* to *.rbxcdn.com works. This URL could be `http://www.roblox.com/Thumbs/Asset.ashx?width=110&height=110&assetId=1818`, for example. A solution to this is to either let users use *.rbxcdn.com URLs as `Content` sources, or create API endpoints that redirect to the image, like /Thumbs/ URLs do.

**Comment by Gskartwii** [comment]
Additionally, [t1-t7, c1-c7].roblox.com seem to be mirrors/proxies for their respective rbxcdn.com URLs, or vice versa. Roblox doesn't accept them either.

**Comment by matthewdean** [comment]
ROBLOX won't allow URLs to point directly to the CDN because that could be used to bypass moderation. When a user uploads a decal, he is able to view it before it is approved by the moderation team, which means it already exists on the CDN. Allowing direct linking would allow unapproved sounds and images to be used in-game which is unacceptable.

**Comment by Gskartwii** [comment]
Now, how do we display avatar headshots or bust thumbnails in-game? It seems like an essential feature.

We are already able to display asset thumbnails and user avatars in-game using `/asset-thumbnail/image` and `/avatar-thumbnail/image` respectively. However, only the JSON endpoint for the two former images is available.

**Comment by matthewdean** [comment]
You may post a separate issue asking for a URL which resolves to headshot thumbnails.

I believe t[0-7] subdomains are for ROBLOX-rendered images, c[0-7] are for assets.
