### ISSUE TITLE
Roblox  reoccuring Default error page

### ISSUE THREAD

**Issue by RobloxFTW** [Anaminus/roblox-bug-tracker#766]
![screenshot 7](https://cloud.githubusercontent.com/assets/17812373/13729304/3e96f816-e94b-11e5-9520-958ba93c8ef0.png)

Whenever I try to go on roblox, this page comes in about 3 seconds. I refresh it, it happens again. I even contacted info.roblox.com but they couldn't fix it. Could you guys help me?

**Comment by ernop** [comment]
1. Does it happen in an incognito window?
2. Does it happen after you clear your cookies?
3. Same as 1 & 2, but in firefox?

**Comment by matthewdean** [comment]
Not enough information to reproduce.
