### ISSUE TITLE
Numeric keypad buttons don't show up as Enum.KeyCode.Keypad#, but as Enum.KeyCode.#, in UserInputService events

### ISSUE THREAD

**Issue by GigsD4X** [Anaminus/roblox-bug-tracker#768]
When checking InputObject.KeyCode from UserInputService events, presses of numbers on the numeric keypad show up as regular buttons on the number row of the keyboard. For example, **instead of** `Enum.KeyCode.KeypadEight`, **you get** `Enum.KeyCode.Eight`, and tools in the backpack are equipped.

This makes it impossible to make use of the keypad, which can potentially be very useful for intuitive controls because it's the only part of keyboards that is arranged in a 3x3 grid :(

**Update:** This seems to be a Studio issue. When playing live, keys are detected properly.

**Comment by JayManLive** [comment]
Really? It works for me. With NumLock on, it shows `Enum.KeyCode.#`. With NumLock on, it shows `Enum.KeyCode.Left`, `Enum.KeyCode.Right`, `Enum.KeyCode.Up`, `Enum.KeyCode.Down`, etc.

**Comment by GigsD4X** [comment]
@JayManLive It should show `Enum.KeyCode.Keypad#` instead of `Enum.KeyCode.#`

**Comment by JayManLive** [comment]
Nah. Pushing the number key would tip the number, and pushing the number on the pad (with NumLock on) would tip the number written out.

**Comment by JayManLive** [comment]
There is no `Keypad0` - `Keypad9` as far as I know. Instead, assign your functions to `Enum.KeyCode.Left`, `Enum.KeyCode.Right` etc., and notify players to turn their NumLock off.

**Comment by GigsD4X** [comment]
http://wiki.roblox.com/index.php?title=API:Enum/KeyCode (see values 256 through 272), let's try to keep this comment thread accurate and as concise as possible so it isn't ignored

**Comment by JayManLive** [comment]
Ah. So it's "Keypad" and the number written out. Funny, cause I have never figured out how to trigger those codes either. For me, it's always just the number written out with NumLock on. And Left, Right, etc. with the NumLock off.
