### ISSUE TITLE
UTF-8 GUI text is not scriptable

### ISSUE THREAD

**Issue by Gskartwii** [Anaminus/roblox-bug-tracker#771]
```
game.StarterGui.ScreenGui.TextLabel.Text = "hukkapätkä!";
```

displays "hukkap" when `game.StarterGui.ScreenGui.TextLabel` is a TextLabel or TextButton.
Happens with both the command bar and scripts.
In the patch where UTF-8 was first enabled, non-ASCII characters would be ignored. In the newest one they cut off the rest of the string.
Entering the string through Studio's Properties window works.

**Comment by Joyesh** [comment]
It's because ROBLOX dosen't like ASCII characters as they can get past their filter.
For example, if I were to type ASCII into the web chat, it would give me an "Error" in red text. In game it either replaces it with ?'s or gets rid of it.

**Comment by Gskartwii** [comment]
Why is UTF-8 allowed on GUIs at all then?

You can get past the filter by creating your own font rendering system anyway.

**Comment by Gskartwii** [comment]
This has now been fixed. The following code will work as expected:

```
script.Parent.Text = string.char(0xC3, 0xA5);
```
