### ISSUE TITLE
Test server issues

### ISSUE THREAD

**Issue by Skywad** [Anaminus/roblox-bug-tracker#774]
![0e6ae2dbe4a714747138c39ef8028a8e](https://cloud.githubusercontent.com/assets/4349005/14264594/0389e61c-fa8e-11e5-898d-f523e4d46fe5.png)
Roblox Studio is no longer able to create test servers.

**Comment by The0neThe0nly** [comment]
Happens to me if I already have a server running in the background. I occasionally get errors for starting multiple players at once as well. Both of these issues should be fixed.

**Comment by BinaryResolved** [comment]
@Skywad Is this still a issue?

**Comment by Skywad** [comment]
No, I do not believe so

**Comment by BinaryResolved** [comment]
@Skywad Mind closing it then?

**Comment by Skywad** [comment]
terribly sorry, I'll get on it
