### ISSUE TITLE
Redirecting to insecure HTTP

### ISSUE THREAD

**Issue by Gskartwii** [Anaminus/roblox-bug-tracker#776]
Roblox recently started using HTTPS in production. It is, however, behaving very odd.

Both http://roblox.com and https://roblox.com redirect to http://www.roblox.com. Additionally, http://www.roblox.com does *not* redirect to HTTPS while it should. Instead, HTTP should always redirect to HTTPS.

**Comment by The0neThe0nly** [comment]
http://www.roblox.com is not redirecting to https://www.roblox.com for me.

**Comment by Gskartwii** [comment]
You're right, fixed.

**Comment by tobyteel** [comment]
Glad you're staying vigilent.  We should have this fixed next week.

**Comment by BinaryResolved** [comment]
@tobyteel Any updates on this?

**Comment by Gskartwii** [comment]
@BinaryResolved http://devforum.roblox.com/t/moving-all-of-roblox-com-to-https-need-your-help/24327

**Comment by BinaryResolved** [comment]
@Gskartwii Thanks.

**Comment by BinaryResolved** [comment]
@tobyteel This is still a issue, if you enter just roblox.com(while signed in) the site then points your browser to `http://www.roblox.com/`. Then that url points your browser to `http://www.roblox.com/home` which is a non HTTPS url.

**Comment by The0neThe0nly** [comment]
@BinaryResolved It is redirecting to HTTPS for me.

**Comment by BinaryResolved** [comment]
@The0neThe0nly It is now for me also. It was fixed a few days after me posting this. Maybe he saw it or maybe they were already aware.

**Comment by Gskartwii** [comment]
Yes, this seems to be fixed.  
There are still some URLs that seems to stay on the protocol they're initially requested on (http://www.roblox.com/avatar-thumbnails?params=[{userId:1}]). but this is probably intentional.
