### ISSUE TITLE
Very urgent bug with trading [website]

### ISSUE THREAD

**Issue by attomicgreen** [Anaminus/roblox-bug-tracker#778]
Recently, there has been a bug involving the trades system when a user spams the same trade (often very low items for expensive things) over and over, and the recipient keeps declining, there is a bug where it will send the trade back to the original sender, even if they decline every single one. This bug should be fixed because some people are already losing a lot of items through this.

**Comment by BinaryResolved** [comment]
I had this happen to me, didn't lose much RAP but I did like the hat I lost.

**Comment by attomicgreen** [comment]
I hope it gets patched soon, so people don't loose things that they bought robux to get.

**Comment by Squidcod** [comment]
Can you please post screenshots of the trade history?  I would also like to have the Name of both accounts involved.  Thanks.

**Comment by attomicgreen** [comment]
Actually, It hasn't happened to me, but I thought it sounded very urgent, because it was spreading fast on the website, so I posted it here so it could get patched before it becomes too big.

**Comment by Squidcod** [comment]
If you can find someone willing to provide that information that will enable us to track down the issue.  Without a specific case to investigate we probably would have a hard time fixing the issue.

**Comment by attomicgreen** [comment]
okay, I have found a user who has had this happen, and here are the screenshots. He told me he declined the trade, but it got completed anyways, with this bug I have just explained.
[The trade history](http://prnt.sc/azm70j)
[The trade itself](http://prnt.sc/azmc3g)

the users involved were Real4207b (who pressed decline) and LightFantom (who sent the trade, got it sent back, and then accepted)

**Comment by matthewdean** [comment]
I'm assuming this has been fixed. If it hasn't, please provide repro steps.

**Comment by L0zz** [comment]
I believe this is what has happened to my son's account recently, Alpherical. MadamDocxtor managed to obtain 4 expensive Limited items. Unforunately the trade history only shows successful trades despite him closing the trade window (effectively cancelling) via clicking X
