### ISSUE TITLE
[FIXED] Sphere Bug 5/7/16

### ISSUE THREAD

**Issue by InfinityGaming** [Anaminus/roblox-bug-tracker#779]
Hey Guys, In Studio And When Ever I Spawn I A Sphere, It Like Glitches Out And Make The Dimension 4,1,2 Anyone having The Same Problem?

![robloxscreenshot05072016_144924346](https://cloud.githubusercontent.com/assets/13459555/15093911/f30c566e-1462-11e6-8cca-db3dc7ffa98e.png)

**Comment by BinaryResolved** [comment]
@InfinityGaming , did you spawn a sphere or a part with a sphere mesh?

**Comment by InfinityGaming** [comment]
Just a sphere

**Comment by InfinityGaming** [comment]
@BinaryResolved JUst a Sphere

**Comment by BinaryResolved** [comment]
@InfinityGaming By default all parts are created with a size of 4,1,2. It makes it distorted because of the size. It's not really a bug, because it works fine. All you have to do is resize it. You can use either, the properties and change it to the size you need. I recommend this way because the other way is a bit glitchy. The other way is to use the size tool. It's a bit glitchy at first but you just have to size it bigger and smaller till it gains proportion.

**Comment by InfinityGaming** [comment]
@BinaryResolved Thanks Man, Having The Same Problem?

**Comment by BinaryResolved** [comment]
@InfinityGaming Mhm.

**Comment by kyle-emmerich** [comment]
Hm, what would be preferable to this behavior? I personally find it annoying when changing the Shape changes the Size, in case I accidentally choose Ball when I meant to do something else.

**Comment by BinaryResolved** [comment]
@kyle-emmerich Neither do I. This is how I wish it would behave. When you create a new part it is the default 4,1,2 size. However if its a ball create is something even. Like 1,1,1 or 2,2,2 or even 4,4,4. I don't care it's just a pain to have to get it to look like a ball when the size is 4,1,2. It looks like some demented oval, and takes more time then I would care for to fix it.

**Comment by kyle-emmerich** [comment]
So another option as opposed to Part that's just "Ball" maybe? I'm not sure if it's easy enough to warrant adding that, since it isn't a separate type or anything.

**Comment by BinaryResolved** [comment]
@kyle-emmerich Seems like it would be some trouble adding something like that. I'm just letting you know how I feel about the issue.

**Comment by InfinityGaming** [comment]
Guys its solved

**Comment by BinaryResolved** [comment]
Ok, close it then.
