### ISSUE TITLE
Cannot follow people directly into games

### ISSUE THREAD

**Issue by bubbaman73** [Anaminus/roblox-bug-tracker#785]
So lately I cant follow people directly into games. what I mean is that i cannot go to their profile and follow them; even if their settings and mine are adequate. When i try to all it does is shows an infinite requesting server screen, https://gyazo.com/5b6198bf7ce9bc39b9eb6d57fe37983c. I have to look through the server lists to join. Ive tried joining multiple peoples games and it still does it.

**Comment by BinaryResolved** [comment]
Same thing for me. It just says "Requesting server..." with the repeating . forever.

**Comment by bubbaman73** [comment]
Yeah one of my close friends is saying this also happens to them?

**Comment by bubbaman73** [comment]
i think this has been resolved
