### ISSUE TITLE
Part Named "GUI" In Camera And Model Named "Status" In Humaniod

### ISSUE THREAD

**Issue by InfinityGaming** [Anaminus/roblox-bug-tracker#788]
Hello. When I Play In Solo Mode I GO In Camera And Find A Part Name "GUI"
Also I Find A Model In My Player Under Humanoid Name "Status"
Please Let Me Know If You Have The Same Problem Or Know How To Fix it 

I Wrote A Script To Temperately Delete It:

-- Bug idk --

function del()

wait()

game.Workspace.Camera.GUI:Remove()

game.Workspace.Player1.Humanoid.Status:Remove()

end

del()

**Comment by BinaryResolved** [comment]
I have this same problem, I thought it was just me. I think it may be one
of the core-scripts because if I deactivate them all it doesn't happen.

**Comment by InfinityGaming** [comment]
@BinaryResolved Good At Least I Know Its Not Like A Virus Or Anything :)

**Comment by JodeRBX** [comment]
Found [the culprit](https://github.com/ROBLOX/Core-Scripts/blob/master/CoreScriptsRoot/Modules/Panel3D.lua#L144) for the GUI part, at least.

To me, the fact that the core scripts themselves rely on the [old local parts hack](http://wiki.roblox.com/index.php?title=Local_parts#Camera) shows just how much ROBLOX needs a fully-supported mechanism for manually changing what gets replicated, when, and to who. But either way,  I'm pretty sure Panel3D is only used when VR is enabled; thus, the part really shouldn't show up in the game hierarchy unless this is this case. I'm going to resubmit this on the core script bug tracker.

**Comment by InfinityGaming** [comment]
@JodeRBX Is It Like A Virus Or Anything?

**Comment by InfinityGaming** [comment]
@JodeRBX Also You Having The Same Problem?

**Comment by JodeRBX** [comment]
I really would just leave it alone, actually. It won't cause you any problems. And yes, both the part and the Status model show up for me too.

**Comment by InfinityGaming** [comment]
@JodeRBX Thanks.

**Comment by kyle-emmerich** [comment]
You probably shouldn't be finding parts in your camera if you're not in VR. I don't think anything will break if you just destroy it.

We had to do this because of the way SurfaceGuis worked up until maybe last week; they needed to be in the workspace or you couldn't raycast against them. However, you no longer need to do that if you set SurfaceGui.AlwaysOnTop = true (which you should do if you're using it for a 3D HUD.)

That being said, putting parts in the camera isn't *that* hacky. The camera isn't inherently a container class, but it is inherently non-replicated. From a design standpoint, it's not terrible.

**Comment by BinaryResolved** [comment]
@kyle-emmerich The only time I notice is when I'm in studio with OverrideCoreScripts unchecked. When its unchecked its not there. So it may be a possible problem with studio communicating with the overridecorescripts folder. But I'm not sure.

**Comment by kyle-emmerich** [comment]
Maybe you have an old/broken version that's being looked up for the override?

**Comment by BinaryResolved** [comment]
I update it daily, last time I did it was about 5 PM yesterday.

-----Original Message-----

**Comment by InfinityGaming** [comment]
So is a virus?

**Comment by InfinityGaming** [comment]
Its Stil there btw

**Comment by kyle-emmerich** [comment]
No, it's not a virus and it'll be fixed on Wednesday night of this upcoming week.

**Comment by InfinityGaming** [comment]
@kyle-emmerich ummm status is still in humanoid is that supposed to be there?

**Comment by kyle-emmerich** [comment]
Not really sure. That's way before my time.

**Comment by InfinityGaming** [comment]
@kyle-emmerich What Does That Mean?

**Comment by InfinityGaming** [comment]
@Quenty HELPPPP

**Comment by BinaryResolved** [comment]
@InfinityGaming That's always been there. It is a unfinished project that was started and was never finished. Not sure why they don't just remove it from the Humanoid. As far as I can see it doesn't do anything. http://wiki.roblox.com/index.php?title=API:Class/Status
