### ISSUE TITLE
BUGS

### ISSUE THREAD

**Issue by DajaGamer** [Anaminus/roblox-bug-tracker#789]
On Mobile devices sometimes some of your charecter body parts arent there
Please fix

**Comment by Quenty** [comment]
Please clarify this bug.

**Comment by bigboybailey** [comment]
He can't.

**Comment by BinaryResolved** [comment]
He can't say what isn't there or anything else? If not then this will most defiantly be ignored.

**Comment by bigboybailey** [comment]
I'm going to assume he's talking about the bug where the 3.0 male's legs are connected to the same joint, making it look like you only have one leg.

**Comment by BinaryResolved** [comment]
We can't just assume, we can't solve bugs off of assumptions.

**Comment by TochigiR** [comment]
I think it's already patched anyway.

**Comment by matthewdean** [comment]
Not enough information to reproduce.
