### ISSUE TITLE
Crash on Playing an Animation that is incorrectly formatted

### ISSUE THREAD

**Issue by Quenty** [Anaminus/roblox-bug-tracker#79]
ROBLOX can be crashed by attempting to play an animation on a player where the animation has been incorrectly formatted (This formatting, not having been documented, seems to follow these rules).

1) The 0 frame needs to have an animation (Not Verified)
2) The animation's keyposes do not contain the same poses
3) You can not try to play animations over each other
4) Animations must be by factors of 0.1 as far as time? (Not verified)

Overall, the system is quite buggy compared to what *can* be scripted.

**Comment by zeux** [comment]
Should be fixed.
