### ISSUE TITLE
Private Modules

### ISSUE THREAD

**Issue by ToastEngine** [Anaminus/roblox-bug-tracker#808]
Requiring a module from a user who doesn't own a module named MainModule doesn't work.

http://wiki.roblox.com/index.php?title=Private_module is what I was talking about

to recreate this, 
1. Create a module of any type
2. Name it "MainModule"
3. Upload to roblox keep locked
4. Require(AssetId) from  another account that doesn't own the module

Output: 
20:10:10.549 - Content failed because HTTP 409 (HTTP/1.1 409 User is not authorized to access Asset.)
20:10:10.550 - Unable to find module for asset id

To make sure it wasn't just the wrong id I also redid it on the account I uploaded the module on works.
Tested it with a group uploading it, everyone in the group can use it.

**Comment by seranok** [comment]
Can you provide a thorough explanation, with repro steps? I'm not sure what you are saying

**Comment by ToastEngine** [comment]
Updated

**Comment by seranok** [comment]
Are you requiring from a server script? Is this in Studio?

**Comment by ToastEngine** [comment]
Its being required from a studio plugin

**Comment by seranok** [comment]
Private modules don't work from Studio because that would allow users to access their source.

**Comment by ToastEngine** [comment]
Even in plugins ? :(
