### ISSUE TITLE
Accessing Selection Table Throws Unspecified Error

### ISSUE THREAD

**Issue by EmptyGroceryBag** [Anaminus/roblox-bug-tracker#813]
I am reluctant to post this because it seems like a simple issue to fix (knowing me, the solution is probably right under my nose) but so far I'm stumped. I'm lead to believe that this is a bug. What's strange is that I wrote a plugin not too long ago that uses Get() and so far I have not had any issues in that regard. I compared the syntax used in the plugin (known working code) with the syntax shown here and it is 100% identical.

The following is the simplest script I could write that accurately reproduced this bug:

s = game:GetService("Selection")
selection = s:Get()

output:

21:11:40.317 - An error occurred
21:11:40.318 - Stack Begin
21:11:40.319 - Script 'Workspace.Script', Line 2
21:11:40.319 - Stack End

As you can see, the error is thrown upon calling Get() on line 2.

The script is (obviously) a direct descendant of Workspace and there are no other instances apart from the default (baseplate, etc...). The same issue also occurs when using "game.Selection". This bug appears to be 100% reproducible in any scenario (apart from plugins, apparently :S).

**Comment by Gskartwii** [comment]
"An error occurred" usually means that you're trying to use a function that is restricted. Selection:Get() is PluginSecurity, and can't be used from scripts. Though, the error message indeed is unspecific.

**Comment by EmptyGroceryBag** [comment]
It appears that it is indeed restricted. Looks like my ignorance has fucked me over again. Do you know of another similar function that can be used in ordinary scripts?

**Comment by Gskartwii** [comment]
No, though you might be able to implement something similar with SelectionBoxes.
