### ISSUE TITLE
A bug that many of players told me.

### ISSUE THREAD

**Issue by Hemowow** [Anaminus/roblox-bug-tracker#829]

**Comment by Hemowow** [comment]
I rpg alot and I haven't played game for a long time.I am back and today i entered a rpg game.I wanted to remove my hats but the button didn't work.I clicked on it,I stepped on it nothing.I tried another game and the same problem is here.I don't know what to do. Also many players said that it wasn't working for them either. Some help needed.

Hemowow

**Comment by Gskartwii** [comment]
It's been removed on purpose.

**Comment by foreverpower** [comment]
This isn't a bug, it was removed intentionally, partly because the new accessory system allows players to wear many more hats than they could before.

http://devforum.roblox.com/t/removing-accessory-dropping-key-shortcut/31214

**Comment by Hemowow** [comment]
Okay thank you! I thought it was a bug becouse I didn't play for a while.

Hemowow
