### ISSUE TITLE
When seated, leg welds do not replicate to other clients

### ISSUE THREAD

**Issue by MerelyRBLX** [Anaminus/roblox-bug-tracker#83]
When your character sits in a Seat or VehicleSeat, on your client your legs appear to be horizontal, but to other clients, your legs are still vertical.

![image](https://f.cloud.github.com/assets/5466234/1146720/5443e394-1e79-11e3-8c56-f02c464bdd9f.png)

**Comment by matthewdean** [comment]
Is this still the case? I joined Trade Hangout recently and noticed that other players' legs were in the proper position when seated.

**Comment by Anaminus** [comment]
Appears to be fixed:
![seat](https://cloud.githubusercontent.com/assets/918097/5838118/87a7528e-a14a-11e4-9bb5-f27aa9f195bd.png)
