### ISSUE TITLE
Plugin errors do not give specific data to track down issue

### ISSUE THREAD

**Issue by Quenty** [Anaminus/roblox-bug-tracker#84]
Issues such as below can be quite an issue.  ROBLOX studio will spew out output, and there is little to nothing we can do to track it down.

<code>
18:22:04.621 - Plugin attempting to set active state for missing button ID - 6
</code>

![image](https://f.cloud.github.com/assets/1774409/1153612/0b84365a-1f27-11e3-9ab1-52669a2abbe4.png)

A simple stack trace or error would be sufficient.

**Comment by matthewdean** [comment]
@Quenty Can you still reproduce this bug?

**Comment by Anaminus** [comment]
I'm just going to close it. It's been a while, and there's no reproduction.
