### ISSUE TITLE
Duplicate friendships

### ISSUE THREAD

**Issue by MerelyRBLX** [Anaminus/roblox-bug-tracker#88]
Because there is not a unique index to enforce the uniqueness of friendships between two users, a user can click the "Accept All" button multiple times and create multiple friendships per friend request.

![image](https://f.cloud.github.com/assets/5466234/1154436/973e500a-1f44-11e3-9d91-bd4aa6ce5f69.png)

**Comment by matthewdean** [comment]
Uniqueness is now enforced.
